	.align 2
DirectSoundWaveData_sc88_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88_organ2::
	.incbin "sound/direct_sound_samples/sc88_organ2.bin"

	.align 2
DirectSoundWaveData_sc88_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88_fretless_bass.bin"

	.align 2
DirectSoundWaveData_jv1080_slap_bass::
	.incbin "sound/direct_sound_samples/jv1080_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88_synth_bass::
	.incbin "sound/direct_sound_samples/sc88_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88_timpani::
	.incbin "sound/direct_sound_samples/sc88_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_electric_guitar::
	.incbin "sound/direct_sound_samples/unused_electric_guitar.bin"

	.align 2
DirectSoundWaveData_unused_sc88_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_unknown_wood_block_low::
	.incbin "sound/direct_sound_samples/unknown_wood_block_low.bin"

	.align 2
DirectSoundWaveData_unknown_wood_block_high::
	.incbin "sound/direct_sound_samples/unknown_wood_block_high.bin"

	.align 2
DirectSoundWaveData_sc88_standard_kick::
	.incbin "sound/direct_sound_samples/sc88_standard_kick.bin"

	.align 2
DirectSoundWaveData_sc88_standard3_snare::
	.incbin "sound/direct_sound_samples/sc88_standard3_snare.bin"

	.align 2
DirectSoundWaveData_sc88_standard_hand_clap::
	.incbin "sound/direct_sound_samples/sc88_standard_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unknown_tom::
	.incbin "sound/direct_sound_samples/unknown_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_unknown_tambourine::
	.incbin "sound/direct_sound_samples/unknown_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88_bongo::
	.incbin "sound/direct_sound_samples/sc88_bongo.bin"

	.align 2
DirectSoundWaveData_sc88_bongo_low::
	.incbin "sound/direct_sound_samples/sc88_bongo_low.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_unknown_cowbell::
	.incbin "sound/direct_sound_samples/unknown_cowbell.bin"

	.align 2
DirectSoundWaveData_unknown_djembe::
	.incbin "sound/direct_sound_samples/unknown_djembe.bin"

	.align 2
DirectSoundWaveData_unknown_anvil_high::
	.incbin "sound/direct_sound_samples/unknown_anvil_high.bin"

	.align 2
DirectSoundWaveData_sc88_standard_bells::
	.incbin "sound/direct_sound_samples/sc88_standard_bells.bin"

	.align 2
DirectSoundWaveData_unknown_anvil_low::
	.incbin "sound/direct_sound_samples/unknown_anvil_low.bin"

	.align 2
DirectSoundWaveData_unknown_ethnic_drum::
	.incbin "sound/direct_sound_samples/unknown_ethnic_drum.bin"

	.align 2
DirectSoundWaveData_unknown_tsuzumi::
	.incbin "sound/direct_sound_samples/unknown_tsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_48::
	.incbin "sound/direct_sound_samples/sc88_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_60::
	.incbin "sound/direct_sound_samples/sc88_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_72::
	.incbin "sound/direct_sound_samples/sc88_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88_piano1_84::
	.incbin "sound/direct_sound_samples/sc88_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88_trumpet_84.bin"

	.align 2
DirectSoundWaveData_unknown_trombone_39::
	.incbin "sound/direct_sound_samples/unknown_trombone_39.bin"

	.align 2
DirectSoundWaveData_unknown_trombone_51::
	.incbin "sound/direct_sound_samples/unknown_trombone_51.bin"

	.align 2
DirectSoundWaveData_sc88_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88_flute::
	.incbin "sound/direct_sound_samples/sc88_flute.bin"

	.align 2
DirectSoundWaveData_sc88_pick_bass::
	.incbin "sound/direct_sound_samples/sc88_pick_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_unknown_church_organ::
	.incbin "sound/direct_sound_samples/unknown_church_organ.bin"

	.align 2
DirectSoundWaveData_emu_ii_pipe_organ::
	.incbin "sound/direct_sound_samples/emu_ii_pipe_organ.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88_square_wave::
	.incbin "sound/direct_sound_samples/sc88_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_8725A2C::
	.incbin "sound/direct_sound_samples/8725A2C.bin"

	.align 2
DirectSoundWaveData_sc88_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_872762C::
	.incbin "sound/direct_sound_samples/872762C.bin"

	.align 2
DirectSoundWaveData_872921C::
	.incbin "sound/direct_sound_samples/872921C.bin"

	.align 2
DirectSoundWaveData_872A5D0::
	.incbin "sound/direct_sound_samples/872A5D0.bin"

	.align 2
DirectSoundWaveData_sc88_wind::
	.incbin "sound/direct_sound_samples/sc88_wind.bin"

	.align 2
DirectSoundWaveData_sc88_bubbles::
	.incbin "sound/direct_sound_samples/sc88_bubbles.bin"

	.align 2
DirectSoundWaveData_872EEA8::
	.incbin "sound/direct_sound_samples/872EEA8.bin"

	.align 2
DirectSoundWaveData_87301B0::
	.incbin "sound/direct_sound_samples/87301B0.bin"

	.align 2
DirectSoundWaveData_unused_acid_bass::
	.incbin "sound/direct_sound_samples/unused_acid_bass.bin"

	.align 2
DirectSoundWaveData_8734298::
	.incbin "sound/direct_sound_samples/8734298.bin"

	.align 2
DirectSoundWaveData_87364A8::
	.incbin "sound/direct_sound_samples/87364A8.bin"

	.align 2
DirectSoundWaveData_sc88_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88_tubular_bell.bin"

	.align 2
DirectSoundWaveData_87385E4::
	.incbin "sound/direct_sound_samples/87385E4.bin"

	.align 2
DirectSoundWaveData_unknown_polysynth::
	.incbin "sound/direct_sound_samples/unknown_polysynth.bin"

	.align 2
DirectSoundWaveData_sc88_harp::
	.incbin "sound/direct_sound_samples/sc88_harp.bin"

	.align 2
DirectSoundWaveData_sc88_xylophone::
	.incbin "sound/direct_sound_samples/sc88_xylophone.bin"

	.align 2
DirectSoundWaveData_873ECD8::
	.incbin "sound/direct_sound_samples/873ECD8.bin"

	.align 2
DirectSoundWaveData_8740818::
	.incbin "sound/direct_sound_samples/8740818.bin"

	.align 2
DirectSoundWaveData_sc88_accordion::
	.incbin "sound/direct_sound_samples/sc88_accordion.bin"

	.align 2
DirectSoundWaveData_87424B0::
	.incbin "sound/direct_sound_samples/87424B0.bin"

	.align 2
DirectSoundWaveData_87430C0::
	.incbin "sound/direct_sound_samples/87430C0.bin"

	.align 2
DirectSoundWaveData_8743C50::
	.incbin "sound/direct_sound_samples/8743C50.bin"

	.align 2
DirectSoundWaveData_87446EC::
	.incbin "sound/direct_sound_samples/87446EC.bin"

	.align 2
DirectSoundWaveData_8745034::
	.incbin "sound/direct_sound_samples/8745034.bin"

	.align 2
DirectSoundWaveData_8745A7C::
	.incbin "sound/direct_sound_samples/8745A7C.bin"

	.align 2
Cry_Bulbasaur::
	.incbin "sound/direct_sound_samples/cry_bulbasaur.bin"

	.align 2
Cry_Ivysaur::
	.incbin "sound/direct_sound_samples/cry_ivysaur.bin"

	.align 2
Cry_Venusaur::
	.incbin "sound/direct_sound_samples/cry_venusaur.bin"

	.align 2
Cry_Charmander::
	.incbin "sound/direct_sound_samples/cry_charmander.bin"

	.align 2
Cry_Charmeleon::
	.incbin "sound/direct_sound_samples/cry_charmeleon.bin"

	.align 2
Cry_Charizard::
	.incbin "sound/direct_sound_samples/cry_charizard.bin"

	.align 2
Cry_Squirtle::
	.incbin "sound/direct_sound_samples/cry_squirtle.bin"

	.align 2
Cry_Wartortle::
	.incbin "sound/direct_sound_samples/cry_wartortle.bin"

	.align 2
Cry_Blastoise::
	.incbin "sound/direct_sound_samples/cry_blastoise.bin"

	.align 2
Cry_Caterpie::
	.incbin "sound/direct_sound_samples/cry_caterpie.bin"

	.align 2
Cry_Metapod::
	.incbin "sound/direct_sound_samples/cry_metapod.bin"

	.align 2
Cry_Butterfree::
	.incbin "sound/direct_sound_samples/cry_butterfree.bin"

	.align 2
Cry_Weedle::
	.incbin "sound/direct_sound_samples/cry_weedle.bin"

	.align 2
Cry_Kakuna::
	.incbin "sound/direct_sound_samples/cry_kakuna.bin"

	.align 2
Cry_Beedrill::
	.incbin "sound/direct_sound_samples/cry_beedrill.bin"

	.align 2
Cry_Pidgey::
	.incbin "sound/direct_sound_samples/cry_pidgey.bin"

	.align 2
Cry_Pidgeotto::
	.incbin "sound/direct_sound_samples/cry_pidgeotto.bin"

	.align 2
Cry_Pidgeot::
	.incbin "sound/direct_sound_samples/cry_pidgeot.bin"

	.align 2
Cry_Rattata::
	.incbin "sound/direct_sound_samples/cry_rattata.bin"

	.align 2
Cry_Raticate::
	.incbin "sound/direct_sound_samples/cry_raticate.bin"

	.align 2
Cry_Spearow::
	.incbin "sound/direct_sound_samples/cry_spearow.bin"

	.align 2
Cry_Fearow::
	.incbin "sound/direct_sound_samples/cry_fearow.bin"

	.align 2
Cry_Ekans::
	.incbin "sound/direct_sound_samples/cry_ekans.bin"

	.align 2
Cry_Arbok::
	.incbin "sound/direct_sound_samples/cry_arbok.bin"

	.align 2
Cry_Pikachu::
	.incbin "sound/direct_sound_samples/cry_pikachu.bin"

	.align 2
Cry_Raichu::
	.incbin "sound/direct_sound_samples/cry_raichu.bin"

	.align 2
Cry_Sandshrew::
	.incbin "sound/direct_sound_samples/cry_sandshrew.bin"

	.align 2
Cry_Sandslash::
	.incbin "sound/direct_sound_samples/cry_sandslash.bin"

	.align 2
Cry_NidoranF::
	.incbin "sound/direct_sound_samples/cry_nidoran_f.bin"

	.align 2
Cry_Nidorina::
	.incbin "sound/direct_sound_samples/cry_nidorina.bin"

	.align 2
Cry_Nidoqueen::
	.incbin "sound/direct_sound_samples/cry_nidoqueen.bin"

	.align 2
Cry_NidoranM::
	.incbin "sound/direct_sound_samples/cry_nidoran_m.bin"

	.align 2
Cry_Nidorino::
	.incbin "sound/direct_sound_samples/cry_nidorino.bin"

	.align 2
Cry_Nidoking::
	.incbin "sound/direct_sound_samples/cry_nidoking.bin"

	.align 2
Cry_Clefairy::
	.incbin "sound/direct_sound_samples/cry_clefairy.bin"

	.align 2
Cry_Clefable::
	.incbin "sound/direct_sound_samples/cry_clefable.bin"

	.align 2
Cry_Vulpix::
	.incbin "sound/direct_sound_samples/cry_vulpix.bin"

	.align 2
Cry_Ninetales::
	.incbin "sound/direct_sound_samples/cry_ninetales.bin"

	.align 2
Cry_Jigglypuff::
	.incbin "sound/direct_sound_samples/cry_jigglypuff.bin"

	.align 2
Cry_Wigglytuff::
	.incbin "sound/direct_sound_samples/cry_wigglytuff.bin"

	.align 2
Cry_Zubat::
	.incbin "sound/direct_sound_samples/cry_zubat.bin"

	.align 2
Cry_Golbat::
	.incbin "sound/direct_sound_samples/cry_golbat.bin"

	.align 2
Cry_Oddish::
	.incbin "sound/direct_sound_samples/cry_oddish.bin"

	.align 2
Cry_Gloom::
	.incbin "sound/direct_sound_samples/cry_gloom.bin"

	.align 2
Cry_Vileplume::
	.incbin "sound/direct_sound_samples/cry_vileplume.bin"

	.align 2
Cry_Paras::
	.incbin "sound/direct_sound_samples/cry_paras.bin"

	.align 2
Cry_Parasect::
	.incbin "sound/direct_sound_samples/cry_parasect.bin"

	.align 2
Cry_Venonat::
	.incbin "sound/direct_sound_samples/cry_venonat.bin"

	.align 2
Cry_Venomoth::
	.incbin "sound/direct_sound_samples/cry_venomoth.bin"

	.align 2
Cry_Diglett::
	.incbin "sound/direct_sound_samples/cry_diglett.bin"

	.align 2
Cry_Dugtrio::
	.incbin "sound/direct_sound_samples/cry_dugtrio.bin"

	.align 2
Cry_Meowth::
	.incbin "sound/direct_sound_samples/cry_meowth.bin"

	.align 2
Cry_Persian::
	.incbin "sound/direct_sound_samples/cry_persian.bin"

	.align 2
Cry_Psyduck::
	.incbin "sound/direct_sound_samples/cry_psyduck.bin"

	.align 2
Cry_Golduck::
	.incbin "sound/direct_sound_samples/cry_golduck.bin"

	.align 2
Cry_Mankey::
	.incbin "sound/direct_sound_samples/cry_mankey.bin"

	.align 2
Cry_Primeape::
	.incbin "sound/direct_sound_samples/cry_primeape.bin"

	.align 2
Cry_Growlithe::
	.incbin "sound/direct_sound_samples/cry_growlithe.bin"

	.align 2
Cry_Arcanine::
	.incbin "sound/direct_sound_samples/cry_arcanine.bin"

	.align 2
Cry_Poliwag::
	.incbin "sound/direct_sound_samples/cry_poliwag.bin"

	.align 2
Cry_Poliwhirl::
	.incbin "sound/direct_sound_samples/cry_poliwhirl.bin"

	.align 2
Cry_Poliwrath::
	.incbin "sound/direct_sound_samples/cry_poliwrath.bin"

	.align 2
Cry_Abra::
	.incbin "sound/direct_sound_samples/cry_abra.bin"

	.align 2
Cry_Kadabra::
	.incbin "sound/direct_sound_samples/cry_kadabra.bin"

	.align 2
Cry_Alakazam::
	.incbin "sound/direct_sound_samples/cry_alakazam.bin"

	.align 2
Cry_Machop::
	.incbin "sound/direct_sound_samples/cry_machop.bin"

	.align 2
Cry_Machoke::
	.incbin "sound/direct_sound_samples/cry_machoke.bin"

	.align 2
Cry_Machamp::
	.incbin "sound/direct_sound_samples/cry_machamp.bin"

	.align 2
Cry_Bellsprout::
	.incbin "sound/direct_sound_samples/cry_bellsprout.bin"

	.align 2
Cry_Weepinbell::
	.incbin "sound/direct_sound_samples/cry_weepinbell.bin"

	.align 2
Cry_Victreebel::
	.incbin "sound/direct_sound_samples/cry_victreebel.bin"

	.align 2
Cry_Tentacool::
	.incbin "sound/direct_sound_samples/cry_tentacool.bin"

	.align 2
Cry_Tentacruel::
	.incbin "sound/direct_sound_samples/cry_tentacruel.bin"

	.align 2
Cry_Geodude::
	.incbin "sound/direct_sound_samples/cry_geodude.bin"

	.align 2
Cry_Graveler::
	.incbin "sound/direct_sound_samples/cry_graveler.bin"

	.align 2
Cry_Golem::
	.incbin "sound/direct_sound_samples/cry_golem.bin"

	.align 2
Cry_Ponyta::
	.incbin "sound/direct_sound_samples/cry_ponyta.bin"

	.align 2
Cry_Rapidash::
	.incbin "sound/direct_sound_samples/cry_rapidash.bin"

	.align 2
Cry_Slowpoke::
	.incbin "sound/direct_sound_samples/cry_slowpoke.bin"

	.align 2
Cry_Slowbro::
	.incbin "sound/direct_sound_samples/cry_slowbro.bin"

	.align 2
Cry_Magnemite::
	.incbin "sound/direct_sound_samples/cry_magnemite.bin"

	.align 2
Cry_Magneton::
	.incbin "sound/direct_sound_samples/cry_magneton.bin"

	.align 2
Cry_Farfetchd::
	.incbin "sound/direct_sound_samples/cry_farfetchd.bin"

	.align 2
Cry_Doduo::
	.incbin "sound/direct_sound_samples/cry_doduo.bin"

	.align 2
Cry_Dodrio::
	.incbin "sound/direct_sound_samples/cry_dodrio.bin"

	.align 2
Cry_Seel::
	.incbin "sound/direct_sound_samples/cry_seel.bin"

	.align 2
Cry_Dewgong::
	.incbin "sound/direct_sound_samples/cry_dewgong.bin"

	.align 2
Cry_Grimer::
	.incbin "sound/direct_sound_samples/cry_grimer.bin"

	.align 2
Cry_Muk::
	.incbin "sound/direct_sound_samples/cry_muk.bin"

	.align 2
Cry_Shellder::
	.incbin "sound/direct_sound_samples/cry_shellder.bin"

	.align 2
Cry_Cloyster::
	.incbin "sound/direct_sound_samples/cry_cloyster.bin"

	.align 2
Cry_Gastly::
	.incbin "sound/direct_sound_samples/cry_gastly.bin"

	.align 2
Cry_Haunter::
	.incbin "sound/direct_sound_samples/cry_haunter.bin"

	.align 2
Cry_Gengar::
	.incbin "sound/direct_sound_samples/cry_gengar.bin"

	.align 2
Cry_Onix::
	.incbin "sound/direct_sound_samples/cry_onix.bin"

	.align 2
Cry_Drowzee::
	.incbin "sound/direct_sound_samples/cry_drowzee.bin"

	.align 2
Cry_Hypno::
	.incbin "sound/direct_sound_samples/cry_hypno.bin"

	.align 2
Cry_Krabby::
	.incbin "sound/direct_sound_samples/cry_krabby.bin"

	.align 2
Cry_Kingler::
	.incbin "sound/direct_sound_samples/cry_kingler.bin"

	.align 2
Cry_Voltorb::
	.incbin "sound/direct_sound_samples/cry_voltorb.bin"

	.align 2
Cry_Electrode::
	.incbin "sound/direct_sound_samples/cry_electrode.bin"

	.align 2
Cry_Exeggcute::
	.incbin "sound/direct_sound_samples/cry_exeggcute.bin"

	.align 2
Cry_Exeggutor::
	.incbin "sound/direct_sound_samples/cry_exeggutor.bin"

	.align 2
Cry_Cubone::
	.incbin "sound/direct_sound_samples/cry_cubone.bin"

	.align 2
Cry_Marowak::
	.incbin "sound/direct_sound_samples/cry_marowak.bin"

	.align 2
Cry_Hitmonlee::
	.incbin "sound/direct_sound_samples/cry_hitmonlee.bin"

	.align 2
Cry_Hitmonchan::
	.incbin "sound/direct_sound_samples/cry_hitmonchan.bin"

	.align 2
Cry_Lickitung::
	.incbin "sound/direct_sound_samples/cry_lickitung.bin"

	.align 2
Cry_Koffing::
	.incbin "sound/direct_sound_samples/cry_koffing.bin"

	.align 2
Cry_Weezing::
	.incbin "sound/direct_sound_samples/cry_weezing.bin"

	.align 2
Cry_Rhyhorn::
	.incbin "sound/direct_sound_samples/cry_rhyhorn.bin"

	.align 2
Cry_Rhydon::
	.incbin "sound/direct_sound_samples/cry_rhydon.bin"

	.align 2
Cry_Chansey::
	.incbin "sound/direct_sound_samples/cry_chansey.bin"

	.align 2
Cry_Tangela::
	.incbin "sound/direct_sound_samples/cry_tangela.bin"

	.align 2
Cry_Kangaskhan::
	.incbin "sound/direct_sound_samples/cry_kangaskhan.bin"

	.align 2
Cry_Horsea::
	.incbin "sound/direct_sound_samples/cry_horsea.bin"

	.align 2
Cry_Seadra::
	.incbin "sound/direct_sound_samples/cry_seadra.bin"

	.align 2
Cry_Goldeen::
	.incbin "sound/direct_sound_samples/cry_goldeen.bin"

	.align 2
Cry_Seaking::
	.incbin "sound/direct_sound_samples/cry_seaking.bin"

	.align 2
Cry_Staryu::
	.incbin "sound/direct_sound_samples/cry_staryu.bin"

	.align 2
Cry_Starmie::
	.incbin "sound/direct_sound_samples/cry_starmie.bin"

	.align 2
Cry_MrMime::
	.incbin "sound/direct_sound_samples/cry_mr_mime.bin"

	.align 2
Cry_Scyther::
	.incbin "sound/direct_sound_samples/cry_scyther.bin"

	.align 2
Cry_Jynx::
	.incbin "sound/direct_sound_samples/cry_jynx.bin"

	.align 2
Cry_Electabuzz::
	.incbin "sound/direct_sound_samples/cry_electabuzz.bin"

	.align 2
Cry_Magmar::
	.incbin "sound/direct_sound_samples/cry_magmar.bin"

	.align 2
Cry_Pinsir::
	.incbin "sound/direct_sound_samples/cry_pinsir.bin"

	.align 2
Cry_Tauros::
	.incbin "sound/direct_sound_samples/cry_tauros.bin"

	.align 2
Cry_Magikarp::
	.incbin "sound/direct_sound_samples/cry_magikarp.bin"

	.align 2
Cry_Gyarados::
	.incbin "sound/direct_sound_samples/cry_gyarados.bin"

	.align 2
Cry_Lapras::
	.incbin "sound/direct_sound_samples/cry_lapras.bin"

	.align 2
Cry_Ditto::
	.incbin "sound/direct_sound_samples/cry_ditto.bin"

	.align 2
Cry_Eevee::
	.incbin "sound/direct_sound_samples/cry_eevee.bin"

	.align 2
Cry_Vaporeon::
	.incbin "sound/direct_sound_samples/cry_vaporeon.bin"

	.align 2
Cry_Jolteon::
	.incbin "sound/direct_sound_samples/cry_jolteon.bin"

	.align 2
Cry_Flareon::
	.incbin "sound/direct_sound_samples/cry_flareon.bin"

	.align 2
Cry_Porygon::
	.incbin "sound/direct_sound_samples/cry_porygon.bin"

	.align 2
Cry_Omanyte::
	.incbin "sound/direct_sound_samples/cry_omanyte.bin"

	.align 2
Cry_Omastar::
	.incbin "sound/direct_sound_samples/cry_omastar.bin"

	.align 2
Cry_Kabuto::
	.incbin "sound/direct_sound_samples/cry_kabuto.bin"

	.align 2
Cry_Kabutops::
	.incbin "sound/direct_sound_samples/cry_kabutops.bin"

	.align 2
Cry_Aerodactyl::
	.incbin "sound/direct_sound_samples/cry_aerodactyl.bin"

	.align 2
Cry_Snorlax::
	.incbin "sound/direct_sound_samples/cry_snorlax.bin"

	.align 2
Cry_Articuno::
	.incbin "sound/direct_sound_samples/cry_articuno.bin"

	.align 2
Cry_Zapdos::
	.incbin "sound/direct_sound_samples/cry_zapdos.bin"

	.align 2
Cry_Moltres::
	.incbin "sound/direct_sound_samples/cry_moltres.bin"

	.align 2
Cry_Dratini::
	.incbin "sound/direct_sound_samples/cry_dratini.bin"

	.align 2
Cry_Dragonair::
	.incbin "sound/direct_sound_samples/cry_dragonair.bin"

	.align 2
Cry_Dragonite::
	.incbin "sound/direct_sound_samples/cry_dragonite.bin"

	.align 2
Cry_Mewtwo::
	.incbin "sound/direct_sound_samples/cry_mewtwo.bin"

	.align 2
Cry_Mew::
	.incbin "sound/direct_sound_samples/cry_mew.bin"

	.align 2
Cry_Chikorita::
	.incbin "sound/direct_sound_samples/cry_chikorita.bin"

	.align 2
Cry_Bayleef::
	.incbin "sound/direct_sound_samples/cry_bayleef.bin"

	.align 2
Cry_Meganium::
	.incbin "sound/direct_sound_samples/cry_meganium.bin"

	.align 2
Cry_Cyndaquil::
	.incbin "sound/direct_sound_samples/cry_cyndaquil.bin"

	.align 2
Cry_Quilava::
	.incbin "sound/direct_sound_samples/cry_quilava.bin"

	.align 2
Cry_Typhlosion::
	.incbin "sound/direct_sound_samples/cry_typhlosion.bin"

	.align 2
Cry_Totodile::
	.incbin "sound/direct_sound_samples/cry_totodile.bin"

	.align 2
Cry_Croconaw::
	.incbin "sound/direct_sound_samples/cry_croconaw.bin"

	.align 2
Cry_Feraligatr::
	.incbin "sound/direct_sound_samples/cry_feraligatr.bin"

	.align 2
Cry_Sentret::
	.incbin "sound/direct_sound_samples/cry_sentret.bin"

	.align 2
Cry_Furret::
	.incbin "sound/direct_sound_samples/cry_furret.bin"

	.align 2
Cry_Hoothoot::
	.incbin "sound/direct_sound_samples/cry_hoothoot.bin"

	.align 2
Cry_Noctowl::
	.incbin "sound/direct_sound_samples/cry_noctowl.bin"

	.align 2
Cry_Ledyba::
	.incbin "sound/direct_sound_samples/cry_ledyba.bin"

	.align 2
Cry_Ledian::
	.incbin "sound/direct_sound_samples/cry_ledian.bin"

	.align 2
Cry_Spinarak::
	.incbin "sound/direct_sound_samples/cry_spinarak.bin"

	.align 2
Cry_Ariados::
	.incbin "sound/direct_sound_samples/cry_ariados.bin"

	.align 2
Cry_Crobat::
	.incbin "sound/direct_sound_samples/cry_crobat.bin"

	.align 2
Cry_Chinchou::
	.incbin "sound/direct_sound_samples/cry_chinchou.bin"

	.align 2
Cry_Lanturn::
	.incbin "sound/direct_sound_samples/cry_lanturn.bin"

	.align 2
Cry_Pichu::
	.incbin "sound/direct_sound_samples/cry_pichu.bin"

	.align 2
Cry_Cleffa::
	.incbin "sound/direct_sound_samples/cry_cleffa.bin"

	.align 2
Cry_Igglybuff::
	.incbin "sound/direct_sound_samples/cry_igglybuff.bin"

	.align 2
Cry_Togepi::
	.incbin "sound/direct_sound_samples/cry_togepi.bin"

	.align 2
Cry_Togetic::
	.incbin "sound/direct_sound_samples/cry_togetic.bin"

	.align 2
Cry_Natu::
	.incbin "sound/direct_sound_samples/cry_natu.bin"

	.align 2
Cry_Xatu::
	.incbin "sound/direct_sound_samples/cry_xatu.bin"

	.align 2
Cry_Mareep::
	.incbin "sound/direct_sound_samples/cry_mareep.bin"

	.align 2
Cry_Flaaffy::
	.incbin "sound/direct_sound_samples/cry_flaaffy.bin"

	.align 2
Cry_Ampharos::
	.incbin "sound/direct_sound_samples/cry_ampharos.bin"

	.align 2
Cry_Bellossom::
	.incbin "sound/direct_sound_samples/cry_bellossom.bin"

	.align 2
Cry_Marill::
	.incbin "sound/direct_sound_samples/cry_marill.bin"

	.align 2
Cry_Azumarill::
	.incbin "sound/direct_sound_samples/cry_azumarill.bin"

	.align 2
Cry_Sudowoodo::
	.incbin "sound/direct_sound_samples/cry_sudowoodo.bin"

	.align 2
Cry_Politoed::
	.incbin "sound/direct_sound_samples/cry_politoed.bin"

	.align 2
Cry_Hoppip::
	.incbin "sound/direct_sound_samples/cry_hoppip.bin"

	.align 2
Cry_Skiploom::
	.incbin "sound/direct_sound_samples/cry_skiploom.bin"

	.align 2
Cry_Jumpluff::
	.incbin "sound/direct_sound_samples/cry_jumpluff.bin"

	.align 2
Cry_Aipom::
	.incbin "sound/direct_sound_samples/cry_aipom.bin"

	.align 2
Cry_Sunkern::
	.incbin "sound/direct_sound_samples/cry_sunkern.bin"

	.align 2
Cry_Sunflora::
	.incbin "sound/direct_sound_samples/cry_sunflora.bin"

	.align 2
Cry_Yanma::
	.incbin "sound/direct_sound_samples/cry_yanma.bin"

	.align 2
Cry_Wooper::
	.incbin "sound/direct_sound_samples/cry_wooper.bin"

	.align 2
Cry_Quagsire::
	.incbin "sound/direct_sound_samples/cry_quagsire.bin"

	.align 2
Cry_Espeon::
	.incbin "sound/direct_sound_samples/cry_espeon.bin"

	.align 2
Cry_Umbreon::
	.incbin "sound/direct_sound_samples/cry_umbreon.bin"

	.align 2
Cry_Murkrow::
	.incbin "sound/direct_sound_samples/cry_murkrow.bin"

	.align 2
Cry_Slowking::
	.incbin "sound/direct_sound_samples/cry_slowking.bin"

	.align 2
Cry_Misdreavus::
	.incbin "sound/direct_sound_samples/cry_misdreavus.bin"

	.align 2
Cry_Unown::
	.incbin "sound/direct_sound_samples/cry_unown.bin"

	.align 2
Cry_Wobbuffet::
	.incbin "sound/direct_sound_samples/cry_wobbuffet.bin"

	.align 2
Cry_Girafarig::
	.incbin "sound/direct_sound_samples/cry_girafarig.bin"

	.align 2
Cry_Pineco::
	.incbin "sound/direct_sound_samples/cry_pineco.bin"

	.align 2
Cry_Forretress::
	.incbin "sound/direct_sound_samples/cry_forretress.bin"

	.align 2
Cry_Dunsparce::
	.incbin "sound/direct_sound_samples/cry_dunsparce.bin"

	.align 2
Cry_Gligar::
	.incbin "sound/direct_sound_samples/cry_gligar.bin"

	.align 2
Cry_Steelix::
	.incbin "sound/direct_sound_samples/cry_steelix.bin"

	.align 2
Cry_Snubbull::
	.incbin "sound/direct_sound_samples/cry_snubbull.bin"

	.align 2
Cry_Granbull::
	.incbin "sound/direct_sound_samples/cry_granbull.bin"

	.align 2
Cry_Qwilfish::
	.incbin "sound/direct_sound_samples/cry_qwilfish.bin"

	.align 2
Cry_Scizor::
	.incbin "sound/direct_sound_samples/cry_scizor.bin"

	.align 2
Cry_Shuckle::
	.incbin "sound/direct_sound_samples/cry_shuckle.bin"

	.align 2
Cry_Heracross::
	.incbin "sound/direct_sound_samples/cry_heracross.bin"

	.align 2
Cry_Sneasel::
	.incbin "sound/direct_sound_samples/cry_sneasel.bin"

	.align 2
Cry_Teddiursa::
	.incbin "sound/direct_sound_samples/cry_teddiursa.bin"

	.align 2
Cry_Ursaring::
	.incbin "sound/direct_sound_samples/cry_ursaring.bin"

	.align 2
Cry_Slugma::
	.incbin "sound/direct_sound_samples/cry_slugma.bin"

	.align 2
Cry_Magcargo::
	.incbin "sound/direct_sound_samples/cry_magcargo.bin"

	.align 2
Cry_Swinub::
	.incbin "sound/direct_sound_samples/cry_swinub.bin"

	.align 2
Cry_Piloswine::
	.incbin "sound/direct_sound_samples/cry_piloswine.bin"

	.align 2
Cry_Corsola::
	.incbin "sound/direct_sound_samples/cry_corsola.bin"

	.align 2
Cry_Remoraid::
	.incbin "sound/direct_sound_samples/cry_remoraid.bin"

	.align 2
Cry_Octillery::
	.incbin "sound/direct_sound_samples/cry_octillery.bin"

	.align 2
Cry_Delibird::
	.incbin "sound/direct_sound_samples/cry_delibird.bin"

	.align 2
Cry_Mantine::
	.incbin "sound/direct_sound_samples/cry_mantine.bin"

	.align 2
Cry_Skarmory::
	.incbin "sound/direct_sound_samples/cry_skarmory.bin"

	.align 2
Cry_Houndour::
	.incbin "sound/direct_sound_samples/cry_houndour.bin"

	.align 2
Cry_Houndoom::
	.incbin "sound/direct_sound_samples/cry_houndoom.bin"

	.align 2
Cry_Kingdra::
	.incbin "sound/direct_sound_samples/cry_kingdra.bin"

	.align 2
Cry_Phanpy::
	.incbin "sound/direct_sound_samples/cry_phanpy.bin"

	.align 2
Cry_Donphan::
	.incbin "sound/direct_sound_samples/cry_donphan.bin"

	.align 2
Cry_Porygon2::
	.incbin "sound/direct_sound_samples/cry_porygon2.bin"

	.align 2
Cry_Stantler::
	.incbin "sound/direct_sound_samples/cry_stantler.bin"

	.align 2
Cry_Smeargle::
	.incbin "sound/direct_sound_samples/cry_smeargle.bin"

	.align 2
Cry_Tyrogue::
	.incbin "sound/direct_sound_samples/cry_tyrogue.bin"

	.align 2
Cry_Hitmontop::
	.incbin "sound/direct_sound_samples/cry_hitmontop.bin"

	.align 2
Cry_Smoochum::
	.incbin "sound/direct_sound_samples/cry_smoochum.bin"

	.align 2
Cry_Elekid::
	.incbin "sound/direct_sound_samples/cry_elekid.bin"

	.align 2
Cry_Magby::
	.incbin "sound/direct_sound_samples/cry_magby.bin"

	.align 2
Cry_Miltank::
	.incbin "sound/direct_sound_samples/cry_miltank.bin"

	.align 2
Cry_Blissey::
	.incbin "sound/direct_sound_samples/cry_blissey.bin"

	.align 2
Cry_Raikou::
	.incbin "sound/direct_sound_samples/cry_raikou.bin"

	.align 2
Cry_Entei::
	.incbin "sound/direct_sound_samples/cry_entei.bin"

	.align 2
Cry_Suicune::
	.incbin "sound/direct_sound_samples/cry_suicune.bin"

	.align 2
Cry_Larvitar::
	.incbin "sound/direct_sound_samples/cry_larvitar.bin"

	.align 2
Cry_Pupitar::
	.incbin "sound/direct_sound_samples/cry_pupitar.bin"

	.align 2
Cry_Tyranitar::
	.incbin "sound/direct_sound_samples/cry_tyranitar.bin"

	.align 2
Cry_Lugia::
	.incbin "sound/direct_sound_samples/cry_lugia.bin"

	.align 2
Cry_HoOh::
	.incbin "sound/direct_sound_samples/cry_ho_oh.bin"

	.align 2
Cry_Celebi::
	.incbin "sound/direct_sound_samples/cry_celebi.bin"

	.align 2
Cry_Kecleon::
	.incbin "sound/direct_sound_samples/cry_kecleon.bin"

	.align 2
Cry_Roselia::
	.incbin "sound/direct_sound_samples/cry_roselia.bin"

	.align 2
Cry_Torkoal::
	.incbin "sound/direct_sound_samples/cry_torkoal.bin"

	.align 2
Cry_Electrike::
	.incbin "sound/direct_sound_samples/cry_electrike.bin"

	.align 2
Cry_Manectric::
	.incbin "sound/direct_sound_samples/cry_manectric.bin"

	.align 2
Cry_Duskull::
	.incbin "sound/direct_sound_samples/cry_duskull.bin"

	.align 2
Cry_Latias::
	.incbin "sound/direct_sound_samples/cry_latias.bin"

	.align 2
Cry_Wynaut::
	.incbin "sound/direct_sound_samples/cry_wynaut.bin"

	.align 2
Cry_Seviper::
	.incbin "sound/direct_sound_samples/cry_seviper.bin"

	.align 2
Cry_Sharpedo::
	.incbin "sound/direct_sound_samples/cry_sharpedo.bin"

	.align 2
Cry_Zangoose::
	.incbin "sound/direct_sound_samples/cry_zangoose.bin"

	.align 2
Cry_Azurill::
	.incbin "sound/direct_sound_samples/cry_azurill.bin"

	.align 2
Cry_Swablu::
	.incbin "sound/direct_sound_samples/cry_swablu.bin"

	.align 2
Cry_Altaria::
	.incbin "sound/direct_sound_samples/cry_altaria.bin"

	.align 2
Cry_Unused265::
	.incbin "sound/direct_sound_samples/cry_unused_265.bin"

	.align 2
Cry_Taillow::
	.incbin "sound/direct_sound_samples/cry_taillow.bin"

	.align 2
Cry_Swellow::
	.incbin "sound/direct_sound_samples/cry_swellow.bin"

	.align 2
Cry_Unused268::
	.incbin "sound/direct_sound_samples/cry_unused_268.bin"

	.align 2
Cry_Spinda::
	.incbin "sound/direct_sound_samples/cry_spinda.bin"

	.align 2
Cry_Torchic::
	.incbin "sound/direct_sound_samples/cry_torchic.bin"

	.align 2
Cry_Combusken::
	.incbin "sound/direct_sound_samples/cry_combusken.bin"

	.align 2
Cry_Blaziken::
	.incbin "sound/direct_sound_samples/cry_blaziken.bin"

	.align 2
Cry_Treecko::
	.incbin "sound/direct_sound_samples/cry_treecko.bin"

	.align 2
Cry_Grovyle::
	.incbin "sound/direct_sound_samples/cry_grovyle.bin"

	.align 2
Cry_Sceptile::
	.incbin "sound/direct_sound_samples/cry_sceptile.bin"

	.align 2
Cry_Mudkip::
	.incbin "sound/direct_sound_samples/cry_mudkip.bin"

	.align 2
Cry_Marshtomp::
	.incbin "sound/direct_sound_samples/cry_marshtomp.bin"

	.align 2
Cry_Swampert::
	.incbin "sound/direct_sound_samples/cry_swampert.bin"

	.align 2
Cry_Pelipper::
	.incbin "sound/direct_sound_samples/cry_pelipper.bin"

	.align 2
Cry_Wingull::
	.incbin "sound/direct_sound_samples/cry_wingull.bin"

	.align 2
Cry_Banette::
	.incbin "sound/direct_sound_samples/cry_banette.bin"

	.align 2
Cry_Shuppet::
	.incbin "sound/direct_sound_samples/cry_shuppet.bin"

	.align 2
Cry_Lotad::
	.incbin "sound/direct_sound_samples/cry_lotad.bin"

	.align 2
Cry_Lombre::
	.incbin "sound/direct_sound_samples/cry_lombre.bin"

	.align 2
Cry_Ludicolo::
	.incbin "sound/direct_sound_samples/cry_ludicolo.bin"

	.align 2
Cry_Seedot::
	.incbin "sound/direct_sound_samples/cry_seedot.bin"

	.align 2
Cry_Nuzleaf::
	.incbin "sound/direct_sound_samples/cry_nuzleaf.bin"

	.align 2
Cry_Shiftry::
	.incbin "sound/direct_sound_samples/cry_shiftry.bin"

	.align 2
Cry_Carvanha::
	.incbin "sound/direct_sound_samples/cry_carvanha.bin"

	.align 2
Cry_Wurmple::
	.incbin "sound/direct_sound_samples/cry_wurmple.bin"

	.align 2
Cry_Silcoon::
	.incbin "sound/direct_sound_samples/cry_silcoon.bin"

	.align 2
Cry_Beautifly::
	.incbin "sound/direct_sound_samples/cry_beautifly.bin"

	.align 2
Cry_Cascoon::
	.incbin "sound/direct_sound_samples/cry_cascoon.bin"

	.align 2
Cry_Dustox::
	.incbin "sound/direct_sound_samples/cry_dustox.bin"

	.align 2
Cry_Ralts::
	.incbin "sound/direct_sound_samples/cry_ralts.bin"

	.align 2
Cry_Kirlia::
	.incbin "sound/direct_sound_samples/cry_kirlia.bin"

	.align 2
Cry_Gardevoir::
	.incbin "sound/direct_sound_samples/cry_gardevoir.bin"

	.align 2
Cry_Slakoth::
	.incbin "sound/direct_sound_samples/cry_slakoth.bin"

	.align 2
Cry_Vigoroth::
	.incbin "sound/direct_sound_samples/cry_vigoroth.bin"

	.align 2
Cry_Slaking::
	.incbin "sound/direct_sound_samples/cry_slaking.bin"

	.align 2
Cry_Nincada::
	.incbin "sound/direct_sound_samples/cry_nincada.bin"

	.align 2
Cry_Ninjask::
	.incbin "sound/direct_sound_samples/cry_ninjask.bin"

	.align 2
Cry_Shedinja::
	.incbin "sound/direct_sound_samples/cry_shedinja.bin"

	.align 2
Cry_Makuhita::
	.incbin "sound/direct_sound_samples/cry_makuhita.bin"

	.align 2
Cry_Hariyama::
	.incbin "sound/direct_sound_samples/cry_hariyama.bin"

	.align 2
Cry_Nosepass::
	.incbin "sound/direct_sound_samples/cry_nosepass.bin"

	.align 2
Cry_Glalie::
	.incbin "sound/direct_sound_samples/cry_glalie.bin"

	.align 2
Cry_Plusle::
	.incbin "sound/direct_sound_samples/cry_plusle.bin"

	.align 2
Cry_Minun::
	.incbin "sound/direct_sound_samples/cry_minun.bin"

	.align 2
Cry_Surskit::
	.incbin "sound/direct_sound_samples/cry_surskit.bin"

	.align 2
Cry_Masquerain::
	.incbin "sound/direct_sound_samples/cry_masquerain.bin"

	.align 2
Cry_Skitty::
	.incbin "sound/direct_sound_samples/cry_skitty.bin"

	.align 2
Cry_Delcatty::
	.incbin "sound/direct_sound_samples/cry_delcatty.bin"

	.align 2
Cry_Gulpin::
	.incbin "sound/direct_sound_samples/cry_gulpin.bin"

	.align 2
Cry_Swalot::
	.incbin "sound/direct_sound_samples/cry_swalot.bin"

	.align 2
Cry_Numel::
	.incbin "sound/direct_sound_samples/cry_numel.bin"

	.align 2
Cry_Camerupt::
	.incbin "sound/direct_sound_samples/cry_camerupt.bin"

	.align 2
Cry_Barboach::
	.incbin "sound/direct_sound_samples/cry_barboach.bin"

	.align 2
Cry_Whiscash::
	.incbin "sound/direct_sound_samples/cry_whiscash.bin"

	.align 2
Cry_Corphish::
	.incbin "sound/direct_sound_samples/cry_corphish.bin"

	.align 2
Cry_Crawdaunt::
	.incbin "sound/direct_sound_samples/cry_crawdaunt.bin"

	.align 2
Cry_Spoink::
	.incbin "sound/direct_sound_samples/cry_spoink.bin"

	.align 2
Cry_Grumpig::
	.incbin "sound/direct_sound_samples/cry_grumpig.bin"

	.align 2
Cry_Trapinch::
	.incbin "sound/direct_sound_samples/cry_trapinch.bin"

	.align 2
Cry_Vibrava::
	.incbin "sound/direct_sound_samples/cry_vibrava.bin"

	.align 2
Cry_Flygon::
	.incbin "sound/direct_sound_samples/cry_flygon.bin"

	.align 2
Cry_Cacnea::
	.incbin "sound/direct_sound_samples/cry_cacnea.bin"

	.align 2
Cry_Cacturne::
	.incbin "sound/direct_sound_samples/cry_cacturne.bin"

	.align 2
Cry_Baltoy::
	.incbin "sound/direct_sound_samples/cry_baltoy.bin"

	.align 2
Cry_Claydol::
	.incbin "sound/direct_sound_samples/cry_claydol.bin"

	.align 2
Cry_Lunatone::
	.incbin "sound/direct_sound_samples/cry_lunatone.bin"

	.align 2
Cry_Solrock::
	.incbin "sound/direct_sound_samples/cry_solrock.bin"

	.align 2
Cry_Feebas::
	.incbin "sound/direct_sound_samples/cry_feebas.bin"

	.align 2
Cry_Milotic::
	.incbin "sound/direct_sound_samples/cry_milotic.bin"

	.align 2
Cry_Absol::
	.incbin "sound/direct_sound_samples/cry_absol.bin"

	.align 2
Cry_Meditite::
	.incbin "sound/direct_sound_samples/cry_meditite.bin"

	.align 2
Cry_Medicham::
	.incbin "sound/direct_sound_samples/cry_medicham.bin"

	.align 2
Cry_Spheal::
	.incbin "sound/direct_sound_samples/cry_spheal.bin"

	.align 2
Cry_Sealeo::
	.incbin "sound/direct_sound_samples/cry_sealeo.bin"

	.align 2
Cry_Walrein::
	.incbin "sound/direct_sound_samples/cry_walrein.bin"

	.align 2
Cry_Clamperl::
	.incbin "sound/direct_sound_samples/cry_clamperl.bin"

	.align 2
Cry_Huntail::
	.incbin "sound/direct_sound_samples/cry_huntail.bin"

	.align 2
Cry_Gorebyss::
	.incbin "sound/direct_sound_samples/cry_gorebyss.bin"

	.align 2
Cry_Lileep::
	.incbin "sound/direct_sound_samples/cry_lileep.bin"

	.align 2
Cry_Cradily::
	.incbin "sound/direct_sound_samples/cry_cradily.bin"

	.align 2
Cry_Anorith::
	.incbin "sound/direct_sound_samples/cry_anorith.bin"

	.align 2
Cry_Armaldo::
	.incbin "sound/direct_sound_samples/cry_armaldo.bin"

	.align 2
Cry_Beldum::
	.incbin "sound/direct_sound_samples/cry_beldum.bin"

	.align 2
Cry_Metang::
	.incbin "sound/direct_sound_samples/cry_metang.bin"

	.align 2
Cry_Metagross::
	.incbin "sound/direct_sound_samples/cry_metagross.bin"

	.align 2
Cry_Bagon::
	.incbin "sound/direct_sound_samples/cry_bagon.bin"

	.align 2
Cry_Shelgon::
	.incbin "sound/direct_sound_samples/cry_shelgon.bin"

	.align 2
Cry_Regirock::
	.incbin "sound/direct_sound_samples/cry_regirock.bin"

	.align 2
Cry_Regice::
	.incbin "sound/direct_sound_samples/cry_regice.bin"

	.align 2
Cry_Registeel::
	.incbin "sound/direct_sound_samples/cry_registeel.bin"

	.align 2
Cry_Castform::
	.incbin "sound/direct_sound_samples/cry_castform.bin"

	.align 2
Cry_Volbeat::
	.incbin "sound/direct_sound_samples/cry_volbeat.bin"

	.align 2
Cry_Illumise::
	.incbin "sound/direct_sound_samples/cry_illumise.bin"

	.align 2
Cry_Poochyena::
	.incbin "sound/direct_sound_samples/cry_poochyena.bin"

	.align 2
Cry_Mightyena::
	.incbin "sound/direct_sound_samples/cry_mightyena.bin"

	.align 2
Cry_Dusclops::
	.incbin "sound/direct_sound_samples/cry_dusclops.bin"

	.align 2
Cry_Sableye::
	.incbin "sound/direct_sound_samples/cry_sableye.bin"

	.align 2
Cry_Mawile::
	.incbin "sound/direct_sound_samples/cry_mawile.bin"

	.align 2
Cry_Aron::
	.incbin "sound/direct_sound_samples/cry_aron.bin"

	.align 2
Cry_Lairon::
	.incbin "sound/direct_sound_samples/cry_lairon.bin"

	.align 2
Cry_Aggron::
	.incbin "sound/direct_sound_samples/cry_aggron.bin"

	.align 2
Cry_Relicanth::
	.incbin "sound/direct_sound_samples/cry_relicanth.bin"

	.align 2
Cry_Luvdisc::
	.incbin "sound/direct_sound_samples/cry_luvdisc.bin"

	.align 2
Cry_Groudon::
	.incbin "sound/direct_sound_samples/cry_groudon.bin"

	.align 2
Cry_Kyogre::
	.incbin "sound/direct_sound_samples/cry_kyogre.bin"

	.align 2
Cry_Rayquaza::
	.incbin "sound/direct_sound_samples/cry_rayquaza.bin"

	.align 2
Cry_Salamence::
	.incbin "sound/direct_sound_samples/cry_salamence.bin"

	.align 2
Cry_Breloom::
	.incbin "sound/direct_sound_samples/cry_breloom.bin"

	.align 2
Cry_Shroomish::
	.incbin "sound/direct_sound_samples/cry_shroomish.bin"

	.align 2
Cry_Linoone::
	.incbin "sound/direct_sound_samples/cry_linoone.bin"

	.align 2
Cry_Tropius::
	.incbin "sound/direct_sound_samples/cry_tropius.bin"

	.align 2
Cry_Wailmer::
	.incbin "sound/direct_sound_samples/cry_wailmer.bin"

	.align 2
Cry_Zigzagoon::
	.incbin "sound/direct_sound_samples/cry_zigzagoon.bin"

	.align 2
Cry_Exploud::
	.incbin "sound/direct_sound_samples/cry_exploud.bin"

	.align 2
Cry_Loudred::
	.incbin "sound/direct_sound_samples/cry_loudred.bin"

	.align 2
Cry_Wailord::
	.incbin "sound/direct_sound_samples/cry_wailord.bin"

	.align 2
Cry_Whismur::
	.incbin "sound/direct_sound_samples/cry_whismur.bin"

	.align 2
Cry_Snorunt::
	.incbin "sound/direct_sound_samples/cry_snorunt.bin"

	.align 2
Cry_Latios::
	.incbin "sound/direct_sound_samples/cry_latios.bin"

	.align 2
Cry_Jirachi::
	.incbin "sound/direct_sound_samples/cry_jirachi.bin"

	.align 2
Cry_Deoxys::
	.incbin "sound/direct_sound_samples/cry_deoxys.bin"

	.align 2
Cry_Chimecho::
	.incbin "sound/direct_sound_samples/cry_chimecho.bin"

	.align 2

Cry_Grookey::
	.incbin "sound/direct_sound_samples/cry_grookey.bin"

	.align 2

Cry_Thwackey::
	.incbin "sound/direct_sound_samples/cry_thwackey.bin"

	.align 2

Cry_Rillaboom::
	.incbin "sound/direct_sound_samples/cry_rillaboom.bin"

	.align 2

Cry_Roserade::
	.incbin "sound/direct_sound_samples/cry_roserade.bin"

	.align 2
	
Cry_Mismagius::
	.incbin "sound/direct_sound_samples/cry_mismagius.bin"

	.align 2
Cry_Honchkrow::
	.incbin "sound/direct_sound_samples/cry_honchkrow.bin"
	
	.align 2
	
Cry_Weavile::
	.incbin "sound/direct_sound_samples/cry_weavile.bin"

	.align 2
Cry_Magnezone::
	.incbin "sound/direct_sound_samples/cry_magnezone.bin"

	.align 2
Cry_Lickilicky::
	.incbin "sound/direct_sound_samples/cry_lickilicky.bin"

	.align 2
Cry_Rhyperior::
	.incbin "sound/direct_sound_samples/cry_rhyperior.bin"

	.align 2
Cry_Tangrowth::
	.incbin "sound/direct_sound_samples/cry_tangrowth.bin"

	.align 2
Cry_Electivire::
	.incbin "sound/direct_sound_samples/cry_electivire.bin"

	.align 2
Cry_Magmortar::
	.incbin "sound/direct_sound_samples/cry_magmortar.bin"

	.align 2
Cry_Togekiss::
	.incbin "sound/direct_sound_samples/cry_togekiss.bin"

	.align 2
Cry_Yanmega::
	.incbin "sound/direct_sound_samples/cry_yanmega.bin"

	.align 2
Cry_Leafeon::
	.incbin "sound/direct_sound_samples/cry_leafeon.bin"

	.align 2
Cry_Glaceon::
	.incbin "sound/direct_sound_samples/cry_glaceon.bin"

	.align 2
Cry_Gliscor::
	.incbin "sound/direct_sound_samples/cry_gliscor.bin"

	.align 2
Cry_Mamoswine::
	.incbin "sound/direct_sound_samples/cry_mamoswine.bin"

	.align 2
Cry_PorygonZ::
	.incbin "sound/direct_sound_samples/cry_porygonZ.bin"

	.align 2
Cry_Gallade::
	.incbin "sound/direct_sound_samples/cry_gallade.bin"

	.align 2
Cry_Probopass::
	.incbin "sound/direct_sound_samples/cry_probopass.bin"

	.align 2
Cry_Dusknoir::
	.incbin "sound/direct_sound_samples/cry_dusknoir.bin"

	.align 2
Cry_Froslass::
	.incbin "sound/direct_sound_samples/cry_froslass.bin"

	.align 2

Cry_Snover::
	.incbin "sound/direct_sound_samples/cry_snover.bin"

	.align 2
Cry_Abomasnow::
	.incbin "sound/direct_sound_samples/cry_abomasnow.bin"

	.align 2

Cry_Sylveon::
	.incbin "sound/direct_sound_samples/cry_sylveon.bin"

	.align 2	

Cry_Yamask::
	.incbin "sound/direct_sound_samples/cry_yamask.bin"

	.align 2
Cry_Cofagrigus::
	.incbin "sound/direct_sound_samples/cry_cofagrigus.bin"

	.align 2
	
Cry_Golett::
	.incbin "sound/direct_sound_samples/cry_golett.bin"

	.align 2
Cry_Golurk::
	.incbin "sound/direct_sound_samples/cry_golurk.bin"

	.align 2

Cry_Tyrunt::
	.incbin "sound/direct_sound_samples/cry_tyrunt.bin"

	.align 2
Cry_Tyrantrum::
	.incbin "sound/direct_sound_samples/cry_tyrantrum.bin"

	.align 2

Cry_Amaura::
	.incbin "sound/direct_sound_samples/cry_amaura.bin"

	.align 2
Cry_Aurorus::
	.incbin "sound/direct_sound_samples/cry_aurorus.bin"

	.align 2

Cry_Ambipom::
	.incbin "sound/direct_sound_samples/cry_ambipom.bin"

	.align 2

Cry_Deino::
	.incbin "sound/direct_sound_samples/cry_deino.bin"

	.align 2
Cry_Zweilous::
	.incbin "sound/direct_sound_samples/cry_zweilous.bin"

	.align 2
Cry_Hydreigon::
	.incbin "sound/direct_sound_samples/cry_hydreigon.bin"

	.align 2
	
Cry_Jangmo_o::
	.incbin "sound/direct_sound_samples/cry_jangmo_o.bin"

	.align 2
Cry_Hakamo_o::
	.incbin "sound/direct_sound_samples/cry_hakamo_o.bin"

	.align 2
Cry_Kommo_o::
	.incbin "sound/direct_sound_samples/cry_kommo_o.bin"

	.align 2

Cry_Skorupi::
	.incbin "sound/direct_sound_samples/cry_skorupi.bin"

	.align 2
Cry_Drapion::
	.incbin "sound/direct_sound_samples/cry_drapion.bin"

	.align 2
	
Cry_Dreepy::
	.incbin "sound/direct_sound_samples/cry_dreepy.bin"

	.align 2

Cry_Drakloak::
	.incbin "sound/direct_sound_samples/cry_drakloak.bin"

	.align 2
Cry_Dragapult::
	.incbin "sound/direct_sound_samples/cry_dragapult.bin"

	.align 2
	
Cry_Wooloo::
	.incbin "sound/direct_sound_samples/cry_wooloo.bin"

	.align 2

Cry_Riolu::
	.incbin "sound/direct_sound_samples/cry_riolu.bin"

	.align 2
Cry_Lucario::
	.incbin "sound/direct_sound_samples/cry_lucario.bin"

	.align 2
	
Cry_Tynamo::
	.incbin "sound/direct_sound_samples/cry_tynamo.bin"

	.align 2
Cry_Eelektrik::
	.incbin "sound/direct_sound_samples/cry_eelektrik.bin"

	.align 2
Cry_Eelektross::
	.incbin "sound/direct_sound_samples/cry_eelektross.bin"

	.align 2
	
Cry_Grubbin::
	.incbin "sound/direct_sound_samples/cry_grubbin.bin"

	.align 2
Cry_Charjabug::
	.incbin "sound/direct_sound_samples/cry_charjabug.bin"

	.align 2
Cry_Vikavolt::
	.incbin "sound/direct_sound_samples/cry_vikavolt.bin"

	.align 2

Cry_Litwick::
	.incbin "sound/direct_sound_samples/cry_litwick.bin"

	.align 2
Cry_Lampent::
	.incbin "sound/direct_sound_samples/cry_lampent.bin"

	.align 2
Cry_Chandelure::
	.incbin "sound/direct_sound_samples/cry_chandelure.bin"

	.align 2
	
Cry_Rowlet::
	.incbin "sound/direct_sound_samples/cry_rowlet.bin"

	.align 2
Cry_Dartrix::
	.incbin "sound/direct_sound_samples/cry_dartrix.bin"

	.align 2
Cry_Decidueye::
	.incbin "sound/direct_sound_samples/cry_decidueye.bin"

	.align 2

Cry_Popplio::
	.incbin "sound/direct_sound_samples/cry_popplio.bin"

	.align 2
Cry_Brionne::
	.incbin "sound/direct_sound_samples/cry_brionne.bin"

	.align 2
Cry_Primarina::
	.incbin "sound/direct_sound_samples/cry_primarina.bin"

	.align 2

Cry_Sobble::
	.incbin "sound/direct_sound_samples/cry_sobble.bin"

	.align 2
Cry_Drizzile::
	.incbin "sound/direct_sound_samples/cry_drizzile.bin"

	.align 2

Cry_Inteleon::
	.incbin "sound/direct_sound_samples/cry_inteleon.bin"

	.align 2
	
Cry_Turtwig::
	.incbin "sound/direct_sound_samples/cry_turtwig.bin"

	.align 2
Cry_Grotle::
	.incbin "sound/direct_sound_samples/cry_grotle.bin"

	.align 2
Cry_Torterra::
	.incbin "sound/direct_sound_samples/cry_torterra.bin"

	.align 2
Cry_Piplup::
	.incbin "sound/direct_sound_samples/cry_piplup.bin"

	.align 2
Cry_Prinplup::
	.incbin "sound/direct_sound_samples/cry_prinplup.bin"

	.align 2
Cry_Empoleon::
	.incbin "sound/direct_sound_samples/cry_empoleon.bin"

	.align 2
	
Cry_Dhelmise::
	.incbin "sound/direct_sound_samples/cry_dhelmise.bin"

	.align 2
	
Cry_Pawniard::
	.incbin "sound/direct_sound_samples/cry_pawniard.bin"

	.align 2
Cry_Bisharp::
	.incbin "sound/direct_sound_samples/cry_bisharp.bin"

	.align 2

Cry_Impidimp::
	.incbin "sound/direct_sound_samples/cry_impidimp.bin"

	.align 2
	
Cry_Morgrem::
	.incbin "sound/direct_sound_samples/cry_morgrem.bin"

	.align 2
Cry_Grimmsnarl::
	.incbin "sound/direct_sound_samples/cry_grimmsnarl.bin"

	.align 2
	
Cry_Salandit::
	.incbin "sound/direct_sound_samples/cry_salandit.bin"

	.align 2
Cry_Salazzle::
	.incbin "sound/direct_sound_samples/cry_salazzle.bin"

	.align 2
	
Cry_Sandygast::
	.incbin "sound/direct_sound_samples/cry_sandygast.bin"

	.align 2
Cry_Palossand::
	.incbin "sound/direct_sound_samples/cry_palossand.bin"

	.align 2
	
Cry_Ferroseed::
	.incbin "sound/direct_sound_samples/cry_ferroseed.bin"

	.align 2
Cry_Ferrothorn::
	.incbin "sound/direct_sound_samples/cry_ferrothorn.bin"

	.align 2
	
Cry_Sandile::
	.incbin "sound/direct_sound_samples/cry_sandile.bin"

	.align 2
Cry_Krokorok::
	.incbin "sound/direct_sound_samples/cry_krokorok.bin"

	.align 2
Cry_Krookodile::
	.incbin "sound/direct_sound_samples/cry_krookodile.bin"

	.align 2
	
Cry_Croagunk::
	.incbin "sound/direct_sound_samples/cry_croagunk.bin"

	.align 2
Cry_Toxicroak::
	.incbin "sound/direct_sound_samples/cry_toxicroak.bin"

	.align 2
	
Cry_Lillipup::
	.incbin "sound/direct_sound_samples/cry_lillipup.bin"

	.align 2
Cry_Herdier::
	.incbin "sound/direct_sound_samples/cry_herdier.bin"

	.align 2
Cry_Stoutland::
	.incbin "sound/direct_sound_samples/cry_stoutland.bin"

	.align 2
	
Cry_Sizzlipede::
	.incbin "sound/direct_sound_samples/cry_sizzlipede.bin"

	.align 2
Cry_Centiskorch::
	.incbin "sound/direct_sound_samples/cry_centiskorch.bin"

	.align 2
	
Cry_Rookidee::
	.incbin "sound/direct_sound_samples/cry_rookidee.bin"

	.align 2
	
Cry_Corvisquire::
	.incbin "sound/direct_sound_samples/cry_corvisquire.bin"

	.align 2
Cry_Corviknight::
	.incbin "sound/direct_sound_samples/cry_corviknight.bin"

	.align 2
	
Cry_Hawlucha::
	.incbin "sound/direct_sound_samples/cry_hawlucha.bin"

	.align 2
	
Cry_Durant::
	.incbin "sound/direct_sound_samples/cry_durant.bin"

	.align 2
	
Cry_Snom::
	.incbin "sound/direct_sound_samples/cry_snom.bin"

	.align 2
	
Cry_Frosmoth::
	.incbin "sound/direct_sound_samples/cry_frosmoth.bin"

	.align 2

Cry_Perserker::
	.incbin "sound/direct_sound_samples/cry_perrserker.bin"

	.align 2
	
Cry_Obstagoon::
	.incbin "sound/direct_sound_samples/cry_obstagoon.bin"

	.align 2
	
Cry_Sirfetchd::
	.incbin "sound/direct_sound_samples/cry_sirfetchd.bin"

	.align 2
	
Cry_Cursola::
	.incbin "sound/direct_sound_samples/cry_cursola.bin"

	.align 2
	
Cry_Mrrime::
	.incbin "sound/direct_sound_samples/cry_mrrime.bin"

	.align 2
	
Cry_Runerigus::
	.incbin "sound/direct_sound_samples/cry_runerigus.bin"

	.align 2
	
Cry_Toxel::
	.incbin "sound/direct_sound_samples/cry_toxel.bin"

	.align 2
	
Cry_Toxtricity::
	.incbin "sound/direct_sound_samples/cry_toxtricity.bin"

	.align 2
	
Cry_Toxtricity_lk::
	.incbin "sound/direct_sound_samples/cry_toxtricity_lk.bin"

	.align 2
	
Cry_Applin::
	.incbin "sound/direct_sound_samples/cry_applin.bin"

	.align 2
	
Cry_Flapple::
	.incbin "sound/direct_sound_samples/cry_flapple.bin"

	.align 2
	
Cry_Appletun::
	.incbin "sound/direct_sound_samples/cry_appletun.bin"

	.align 2
	
Cry_Duraludon::
	.incbin "sound/direct_sound_samples/cry_duraludon.bin"

	.align 2
	
Cry_Cottonee::
	.incbin "sound/direct_sound_samples/cry_cottonee.bin"

	.align 2
	
Cry_Whimsicott::
	.incbin "sound/direct_sound_samples/cry_whimsicott.bin"

	.align 2
	
Cry_Hippopotas::
	.incbin "sound/direct_sound_samples/cry_hippopotas.bin"

	.align 2
	
Cry_Hippowdon::
	.incbin "sound/direct_sound_samples/cry_hippowdon.bin"

	.align 2
	
Cry_Silicobra::
	.incbin "sound/direct_sound_samples/cry_silicobra.bin"

	.align 2
	
Cry_Sandaconda::
	.incbin "sound/direct_sound_samples/cry_sandaconda.bin"

	.align 2
	
Cry_Combee::
	.incbin "sound/direct_sound_samples/cry_combee.bin"

	.align 2
	
Cry_Vespiquen::
	.incbin "sound/direct_sound_samples/cry_vespiquen.bin"

	.align 2
	
Cry_Pancham::
	.incbin "sound/direct_sound_samples/cry_pancham.bin"

	.align 2
	
Cry_Pangoro::
	.incbin "sound/direct_sound_samples/cry_pangoro.bin"

	.align 2
	
Cry_Skrelp::
	.incbin "sound/direct_sound_samples/cry_skrelp.bin"

	.align 2
	
Cry_Dragalge::
	.incbin "sound/direct_sound_samples/cry_dragalge.bin"

	.align 2
	
Cry_Stufful::
	.incbin "sound/direct_sound_samples/cry_stufful.bin"

	.align 2
	
Cry_Bewear::
	.incbin "sound/direct_sound_samples/cry_bewear.bin"

	.align 2
	
Cry_Pumpkaboo::
	.incbin "sound/direct_sound_samples/cry_pumpkaboo.bin"

	.align 2
	
Cry_Gourgeist::
	.incbin "sound/direct_sound_samples/cry_gourgeist.bin"

	.align 2
	
Cry_Frillish::
	.incbin "sound/direct_sound_samples/cry_frillish.bin"

	.align 2
	
Cry_Jellicent::
	.incbin "sound/direct_sound_samples/cry_jellicent.bin"

	.align 2
	
Cry_Rockruff::
	.incbin "sound/direct_sound_samples/cry_rockruff.bin"

	.align 2
	
Cry_Lycanroc_Day::
	.incbin "sound/direct_sound_samples/cry_lycanroc_day.bin"

	.align 2
	
Cry_Lycanroc_Night::
	.incbin "sound/direct_sound_samples/cry_lycanroc_night.bin"

	.align 2
	
Cry_Lycanroc_Dusk::
	.incbin "sound/direct_sound_samples/cry_lycanroc_dusk.bin"

	.align 2
	
Cry_Regigigas::
	.incbin "sound/direct_sound_samples/cry_regigigas.bin"

	.align 2
	
Cry_Floette::
	.incbin "sound/direct_sound_samples/cry_floette.bin"

	.align 2
	
Cry_Snivy::
	.incbin "sound/direct_sound_samples/cry_snivy.bin"

	.align 2
	
Cry_Servine::
	.incbin "sound/direct_sound_samples/cry_servine.bin"

	.align 2
	
Cry_Serperior::
	.incbin "sound/direct_sound_samples/cry_serperior.bin"

	.align 2
	
Cry_Milcery::
	.incbin "sound/direct_sound_samples/cry_milcery.bin"

	.align 2
	
Cry_Alcremie::
	.incbin "sound/direct_sound_samples/cry_alcremie.bin"

	.align 2
	
Cry_Budew::
	.incbin "sound/direct_sound_samples/cry_budew.bin"

	.align 2
	
Cry_Chingling::
	.incbin "sound/direct_sound_samples/cry_chingling.bin"

	.align 2
	
Cry_Bonsly::
	.incbin "sound/direct_sound_samples/cry_bonsly.bin"

	.align 2
	
Cry_Mimejr::
	.incbin "sound/direct_sound_samples/cry_mimejr.bin"

	.align 2
	
Cry_Happiny::
	.incbin "sound/direct_sound_samples/cry_happiny.bin"

	.align 2
	
Cry_Munchlax::
	.incbin "sound/direct_sound_samples/cry_munchlax.bin"

	.align 2
	
Cry_Mantyke::
	.incbin "sound/direct_sound_samples/cry_mantyke.bin"

	.align 2
	
Cry_Mega_Banette::
	.incbin "sound/direct_sound_samples/cry_not_mega_banette.bin"

	.align 2
	
Cry_Mega_Abomasnow::
	.incbin "sound/direct_sound_samples/cry_not_mega_abomasnow.bin"

	.align 2
	
Cry_Mega_Absol::
	.incbin "sound/direct_sound_samples/cry_not_mega_absol.bin"

	.align 2
	
Cry_Mega_Mawile::
	.incbin "sound/direct_sound_samples/cry_not_mega_mawile.bin"

	.align 2
	
Cry_Mega_Sableye::
	.incbin "sound/direct_sound_samples/cry_not_mega_sableye.bin"

	.align 2
Cry_Mega_Altaria::
	.incbin "sound/direct_sound_samples/cry_not_mega_altaria.bin"

	.align 2
	
Cry_Mega_Sharpedo::
	.incbin "sound/direct_sound_samples/cry_not_mega_sharpedo.bin"

	.align 2
	
Cry_Mega_Pidgeot::
	.incbin "sound/direct_sound_samples/cry_not_mega_pidgeot.bin"

	.align 2
Cry_Mega_Glalie::
	.incbin "sound/direct_sound_samples/cry_not_mega_glalie.bin"

	.align 2
	
Cry_Mega_Camerupt::
	.incbin "sound/direct_sound_samples/cry_not_mega_camerupt.bin"

	.align 2
	
Cry_Mega_Beedrill::
	.incbin "sound/direct_sound_samples/cry_not_mega_beedrill.bin"

	.align 2
	
Cry_Mega_Houndoom::
	.incbin "sound/direct_sound_samples/cry_not_mega_houndoom.bin"

	.align 2
	
Cry_Chespin::
	.incbin "sound/direct_sound_samples/cry_not_chespin.bin"

	.align 2
	
Cry_Quilladin::
	.incbin "sound/direct_sound_samples/cry_not_quilladin.bin"

	.align 2
	
Cry_Chesnaught::
	.incbin "sound/direct_sound_samples/cry_not_chesnaught.bin"

	.align 2
	
Cry_Chimchar::
	.incbin "sound/direct_sound_samples/cry_not_chimchar.bin"

	.align 2
	
Cry_Monferno::
	.incbin "sound/direct_sound_samples/cry_not_monferno.bin"

	.align 2
	
Cry_Infernape::
	.incbin "sound/direct_sound_samples/cry_not_infernape.bin"

	.align 2
	
Cry_Regieleki::
	.incbin "sound/direct_sound_samples/cry_regieleki.bin"

	.align 2
	
Cry_Regidrago::
	.incbin "sound/direct_sound_samples/cry_regidrago.bin"

	.align 2
	
Cry_Wintass::
	.incbin "sound/direct_sound_samples/cry_wintass.bin"

	.align 2
	
Cry_Goomy::
	.incbin "sound/direct_sound_samples/cry_not_goomy.bin"

	.align 2
	
Cry_Sliggoo::
	.incbin "sound/direct_sound_samples/cry_not_sliggoo.bin"

	.align 2
	
Cry_Goodra::
	.incbin "sound/direct_sound_samples/cry_not_goodra.bin"

	.align 2
	
Cry_Stunfisk::
	.incbin "sound/direct_sound_samples/cry_not_stunfisk.bin"

	.align 2
	
Cry_Solosis::
	.incbin "sound/direct_sound_samples/cry_not_solosis.bin"

	.align 2
	
Cry_Duosion::
	.incbin "sound/direct_sound_samples/cry_not_duosion.bin"

	.align 2
	
Cry_Reuniclus::
	.incbin "sound/direct_sound_samples/cry_not_reuniclus.bin"

	.align 2
	
Cry_Vullaby::
	.incbin "sound/direct_sound_samples/cry_not_vullaby.bin"

	.align 2
	
Cry_Mandibuzz::
	.incbin "sound/direct_sound_samples/cry_not_mandibuzz.bin"

	.align 2
	
Cry_Drilbur::
	.incbin "sound/direct_sound_samples/cry_not_drilbur.bin"

	.align 2
	
Cry_Excadrill::
	.incbin "sound/direct_sound_samples/cry_not_excadrill.bin"

	.align 2

Cry_Honedge_Monado::
	.incbin "sound/direct_sound_samples/cry_honedge_monado.bin"

	.align 2

Cry_Wyrdeer::
	.incbin "sound/direct_sound_samples/cry_wyrdeer.bin"
	.align 2
Cry_Kleavor::
	.incbin "sound/direct_sound_samples/cry_kleavor.bin"
	.align 2
Cry_Ursaluna::
	.incbin "sound/direct_sound_samples/cry_ursaluna.bin"
	.align 2
Cry_Sneasler::
	.incbin "sound/direct_sound_samples/cry_sneasler.bin"
	.align 2
Cry_Overqwil::
	.incbin "sound/direct_sound_samples/cry_overqwil.bin"
	.align 2
Cry_Kingambit::
	.incbin "sound/direct_sound_samples/cry_kingambit.bin"
	.align 2
Cry_Dudunsparce::
	.incbin "sound/direct_sound_samples/cry_dudunsparce.bin"
	.align 2
Cry_Clodsire::
	.incbin "sound/direct_sound_samples/cry_clodsire.bin"
	.align 2
Cry_Annihilape::
	.incbin "sound/direct_sound_samples/cry_annihilape.bin"
	.align 2
Cry_Farigiraf::
	.incbin "sound/direct_sound_samples/cry_farigiraf.bin"
	.align 2
Cry_Prinpawn::
	.incbin "sound/direct_sound_samples/cry_prinpawn.bin"
	.align 2
Cry_Coureen::
	.incbin "sound/direct_sound_samples/cry_coureen.bin"
	.align 2
Cry_Kincurs::
	.incbin "sound/direct_sound_samples/cry_kincurs.bin"
	.align 2
Cry_Posord::
	.incbin "sound/direct_sound_samples/cry_posord.bin"
	.align 2

DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_88D6978::
	.incbin "sound/direct_sound_samples/88D6978.bin"

	.align 2
DirectSoundWaveData_sc88_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_88DBBC0::
	.incbin "sound/direct_sound_samples/88DBBC0.bin"

	.align 2
DirectSoundWaveData_88DC220::
	.incbin "sound/direct_sound_samples/88DC220.bin"

	.align 2
DirectSoundWaveData_88DC704::
	.incbin "sound/direct_sound_samples/88DC704.bin"

	.align 2
DirectSoundWaveData_88DD054::
	.incbin "sound/direct_sound_samples/88DD054.bin"

	.align 2
DirectSoundWaveData_88DDAC4::
	.incbin "sound/direct_sound_samples/88DDAC4.bin"

	.align 2
DirectSoundWaveData_88DDDE4::
	.incbin "sound/direct_sound_samples/88DDDE4.bin"

	.align 2
DirectSoundWaveData_88DEA6C::
	.incbin "sound/direct_sound_samples/88DEA6C.bin"

	.align 2
DirectSoundWaveData_88DF08C::
	.incbin "sound/direct_sound_samples/88DF08C.bin"

	.align 2
DirectSoundWaveData_88DF414::
	.incbin "sound/direct_sound_samples/88DF414.bin"

	.align 2
DirectSoundWaveData_88E01F8::
	.incbin "sound/direct_sound_samples/88E01F8.bin"

	.align 2
DirectSoundWaveData_88E0B68::
	.incbin "sound/direct_sound_samples/88E0B68.bin"

	.align 2
DirectSoundWaveData_88E0F04::
	.incbin "sound/direct_sound_samples/88E0F04.bin"

	.align 2
DirectSoundWaveData_88E16B8::
	.incbin "sound/direct_sound_samples/88E16B8.bin"

	.align 2
DirectSoundWaveData_88E2414::
	.incbin "sound/direct_sound_samples/88E2414.bin"

	.align 2
DirectSoundWaveData_88E2658::
	.incbin "sound/direct_sound_samples/88E2658.bin"

	.align 2
DirectSoundWaveData_88E3498::
	.incbin "sound/direct_sound_samples/88E3498.bin"

	.align 2
DirectSoundWaveData_88E3DEC::
	.incbin "sound/direct_sound_samples/88E3DEC.bin"

	.align 2
DirectSoundWaveData_88E4140::
	.incbin "sound/direct_sound_samples/88E4140.bin"

	.align 2
DirectSoundWaveData_88E4774::
	.incbin "sound/direct_sound_samples/88E4774.bin"

	.align 2
DirectSoundWaveData_88E53E0::
	.incbin "sound/direct_sound_samples/88E53E0.bin"

	.align 2
DirectSoundWaveData_88E5978::
	.incbin "sound/direct_sound_samples/88E5978.bin"

	.align 2
DirectSoundWaveData_88E647C::
	.incbin "sound/direct_sound_samples/88E647C.bin"

	.align 2
DirectSoundWaveData_88E6A80::
	.incbin "sound/direct_sound_samples/88E6A80.bin"

	.align 2
DirectSoundWaveData_88E6C78::
	.incbin "sound/direct_sound_samples/88E6C78.bin"

	.align 2
DirectSoundWaveData_88E75DC::
	.incbin "sound/direct_sound_samples/88E75DC.bin"

	.align 2
DirectSoundWaveData_88E8568::
	.incbin "sound/direct_sound_samples/88E8568.bin"

	.align 2
DirectSoundWaveData_88E8BA0::
	.incbin "sound/direct_sound_samples/88E8BA0.bin"

	.align 2
DirectSoundWaveData_88E9674::
	.incbin "sound/direct_sound_samples/88E9674.bin"

	.align 2
DirectSoundWaveData_88EA5B8::
	.incbin "sound/direct_sound_samples/88EA5B8.bin"

	.align 2
DirectSoundWaveData_88EAB30::
	.incbin "sound/direct_sound_samples/88EAB30.bin"

	.align 2
DirectSoundWaveData_88EB97C::
	.incbin "sound/direct_sound_samples/88EB97C.bin"

	.align 2
DirectSoundWaveData_88EC884::
	.incbin "sound/direct_sound_samples/88EC884.bin"

	.align 2
DirectSoundWaveData_88ED358::
	.incbin "sound/direct_sound_samples/88ED358.bin"

	.align 2
DirectSoundWaveData_88EDEEC::
	.incbin "sound/direct_sound_samples/88EDEEC.bin"

	.align 2
DirectSoundWaveData_88EE8C4::
	.incbin "sound/direct_sound_samples/88EE8C4.bin"

	.align 2
DirectSoundWaveData_88EEF04::
	.incbin "sound/direct_sound_samples/88EEF04.bin"

	.align 2
DirectSoundWaveData_88EF9E4::
	.incbin "sound/direct_sound_samples/88EF9E4.bin"

	.align 2
DirectSoundWaveData_88F0020::
	.incbin "sound/direct_sound_samples/88F0020.bin"

	.align 2
DirectSoundWaveData_88F0738::
	.incbin "sound/direct_sound_samples/88F0738.bin"

	.align 2
DirectSoundWaveData_88F1074::
	.incbin "sound/direct_sound_samples/88F1074.bin"

	.align 2
DirectSoundWaveData_88F1830::
	.incbin "sound/direct_sound_samples/88F1830.bin"

	.align 2
DirectSoundWaveData_88F1D94::
	.incbin "sound/direct_sound_samples/88F1D94.bin"

	.align 2
DirectSoundWaveData_88F2B08::
	.incbin "sound/direct_sound_samples/88F2B08.bin"

	.align 2
DirectSoundWaveData_88F2F84::
	.incbin "sound/direct_sound_samples/88F2F84.bin"

	.align 2
DirectSoundWaveData_88F3470::
	.incbin "sound/direct_sound_samples/88F3470.bin"

	.align 2
DirectSoundWaveData_88F3C38::
	.incbin "sound/direct_sound_samples/88F3C38.bin"

	.align 2
DirectSoundWaveData_88F4834::
	.incbin "sound/direct_sound_samples/88F4834.bin"

	.align 2
DirectSoundWaveData_88F4BAC::
	.incbin "sound/direct_sound_samples/88F4BAC.bin"

	.align 2
DirectSoundWaveData_88F5368::
	.incbin "sound/direct_sound_samples/88F5368.bin"

	.align 2
DirectSoundWaveData_88F5FCC::
	.incbin "sound/direct_sound_samples/88F5FCC.bin"

	.align 2
DirectSoundWaveData_88F6498::
	.incbin "sound/direct_sound_samples/88F6498.bin"

	.align 2
DirectSoundWaveData_sc88_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"

	.align 2
DirectSoundWaveData_1016ce4::
	.incbin "sound/direct_sound_samples/1016ce4.bin"

	.align 2
DirectSoundWaveData_101a25c::
	.incbin "sound/direct_sound_samples/101a25c.bin"

	.align 2
DirectSoundWaveData_101d59c::
	.incbin "sound/direct_sound_samples/101d59c.bin"

	.align 2
DirectSoundWaveData_102014c::
	.incbin "sound/direct_sound_samples/102014c.bin"

	.align 2
DirectSoundWaveData_10227a4::
	.incbin "sound/direct_sound_samples/10227a4.bin"

	.align 2
DirectSoundWaveData_10250c8::
	.incbin "sound/direct_sound_samples/10250c8.bin"

	.align 2
DirectSoundWaveData_1026e7c::
	.incbin "sound/direct_sound_samples/1026e7c.bin"

	.align 2
DirectSoundWaveData_1028c84::
	.incbin "sound/direct_sound_samples/1028c84.bin"

	.align 2
DirectSoundWaveData_102a948::
	.incbin "sound/direct_sound_samples/102a948.bin"

	.align 2
DirectSoundWaveData_102c284::
	.incbin "sound/direct_sound_samples/102c284.bin"

	.align 2
DirectSoundWaveData_102d580::
	.incbin "sound/direct_sound_samples/102d580.bin"

	.align 2
DirectSoundWaveData_102ecfc::
	.incbin "sound/direct_sound_samples/102ecfc.bin"

	.align 2
DirectSoundWaveData_102f878::
	.incbin "sound/direct_sound_samples/102f878.bin"

	.align 2
DirectSoundWaveData_1030404::
	.incbin "sound/direct_sound_samples/1030404.bin"

	.align 2
DirectSoundWaveData_1030e44::
	.incbin "sound/direct_sound_samples/1030e44.bin"

	.align 2
DirectSoundWaveData_1031628::
	.incbin "sound/direct_sound_samples/1031628.bin"

	.align 2
DirectSoundWaveData_10319fc::
	.incbin "sound/direct_sound_samples/10319fc.bin"

	.align 2
DirectSoundWaveData_1031d54::
	.incbin "sound/direct_sound_samples/1031d54.bin"

	.align 2
DirectSoundWaveData_1031f08::
	.incbin "sound/direct_sound_samples/1031f08.bin"

	.align 2
DirectSoundWaveData_1032108::
	.incbin "sound/direct_sound_samples/1032108.bin"

	.align 2
DirectSoundWaveData_103218c::
	.incbin "sound/direct_sound_samples/103218c.bin"

	.align 2
DirectSoundWaveData_1032970::
	.incbin "sound/direct_sound_samples/1032970.bin"

	.align 2
DirectSoundWaveData_1032ea4::
	.incbin "sound/direct_sound_samples/1032ea4.bin"

	.align 2
DirectSoundWaveData_103327c::
	.incbin "sound/direct_sound_samples/103327c.bin"

	.align 2
DirectSoundWaveData_10334ac::
	.incbin "sound/direct_sound_samples/10334ac.bin"

	.align 2
DirectSoundWaveData_1033654::
	.incbin "sound/direct_sound_samples/1033654.bin"

	.align 2
DirectSoundWaveData_10337c8::
	.incbin "sound/direct_sound_samples/10337c8.bin"

	.align 2
DirectSoundWaveData_10338f8::
	.incbin "sound/direct_sound_samples/10338f8.bin"

	.align 2
DirectSoundWaveData_1035328::
	.incbin "sound/direct_sound_samples/1035328.bin"

	.align 2
DirectSoundWaveData_1036770::
	.incbin "sound/direct_sound_samples/1036770.bin"

	.align 2
DirectSoundWaveData_1037728::
	.incbin "sound/direct_sound_samples/1037728.bin"

	.align 2
DirectSoundWaveData_103858c::
	.incbin "sound/direct_sound_samples/103858c.bin"

	.align 2
DirectSoundWaveData_1038818::
	.incbin "sound/direct_sound_samples/1038818.bin"

	.align 2
DirectSoundWaveData_10389a0::
	.incbin "sound/direct_sound_samples/10389a0.bin"

	.align 2
DirectSoundWaveData_1038aac::
	.incbin "sound/direct_sound_samples/1038aac.bin"

	.align 2
DirectSoundWaveData_1038b20::
	.incbin "sound/direct_sound_samples/1038b20.bin"

	.align 2
DirectSoundWaveData_1038c14::
	.incbin "sound/direct_sound_samples/1038c14.bin"

	.align 2
DirectSoundWaveData_1038e48::
	.incbin "sound/direct_sound_samples/1038e48.bin"

	.align 2
DirectSoundWaveData_1038ee8::
	.incbin "sound/direct_sound_samples/1038ee8.bin"

	.align 2
DirectSoundWaveData_1039034::
	.incbin "sound/direct_sound_samples/1039034.bin"

	.align 2
DirectSoundWaveData_1039204::
	.incbin "sound/direct_sound_samples/1039204.bin"

	.align 2
DirectSoundWaveData_1039354::
	.incbin "sound/direct_sound_samples/1039354.bin"

	.align 2
DirectSoundWaveData_1039410::
	.incbin "sound/direct_sound_samples/1039410.bin"

	.align 2
DirectSoundWaveData_1039740::
	.incbin "sound/direct_sound_samples/1039740.bin"

	.align 2
DirectSoundWaveData_103b0e4::
	.incbin "sound/direct_sound_samples/103b0e4.bin"

	.align 2
DirectSoundWaveData_103c84c::
	.incbin "sound/direct_sound_samples/103c84c.bin"

	.align 2
DirectSoundWaveData_103d62c::
	.incbin "sound/direct_sound_samples/103d62c.bin"

	.align 2
DirectSoundWaveData_103df8c::
	.incbin "sound/direct_sound_samples/103df8c.bin"

	.align 2
DirectSoundWaveData_103e954::
	.incbin "sound/direct_sound_samples/103e954.bin"

	.align 2
DirectSoundWaveData_103f0dc::
	.incbin "sound/direct_sound_samples/103f0dc.bin"

	.align 2
DirectSoundWaveData_103f730::
	.incbin "sound/direct_sound_samples/103f730.bin"

	.align 2
DirectSoundWaveData_103fb80::
	.incbin "sound/direct_sound_samples/103fb80.bin"

	.align 2
DirectSoundWaveData_103fde4::
	.incbin "sound/direct_sound_samples/103fde4.bin"

	.align 2
DirectSoundWaveData_10403e8::
	.incbin "sound/direct_sound_samples/10403e8.bin"

	.align 2
DirectSoundWaveData_104061c::
	.incbin "sound/direct_sound_samples/104061c.bin"

	.align 2
DirectSoundWaveData_1040744::
	.incbin "sound/direct_sound_samples/1040744.bin"

	.align 2
DirectSoundWaveData_10407e8::
	.incbin "sound/direct_sound_samples/10407e8.bin"

	.align 2
DirectSoundWaveData_1041758::
	.incbin "sound/direct_sound_samples/1041758.bin"

	.align 2
DirectSoundWaveData_1041e54::
	.incbin "sound/direct_sound_samples/1041e54.bin"

	.align 2
DirectSoundWaveData_10423ec::
	.incbin "sound/direct_sound_samples/10423ec.bin"

	.align 2
DirectSoundWaveData_10431a8::
	.incbin "sound/direct_sound_samples/10431a8.bin"

	.align 2
DirectSoundWaveData_1044010::
	.incbin "sound/direct_sound_samples/1044010.bin"

	.align 2
DirectSoundWaveData_1044d98::
	.incbin "sound/direct_sound_samples/1044d98.bin"

	.align 2
DirectSoundWaveData_10455f8::
	.incbin "sound/direct_sound_samples/10455f8.bin"

	.align 2
DirectSoundWaveData_1045c10::
	.incbin "sound/direct_sound_samples/1045c10.bin"

	.align 2
DirectSoundWaveData_1045f60::
	.incbin "sound/direct_sound_samples/1045f60.bin"

	.align 2
DirectSoundWaveData_1046468::
	.incbin "sound/direct_sound_samples/1046468.bin"

	.align 2
DirectSoundWaveData_1046794::
	.incbin "sound/direct_sound_samples/1046794.bin"

	.align 2
DirectSoundWaveData_10468cc::
	.incbin "sound/direct_sound_samples/10468cc.bin"

	.align 2
DirectSoundWaveData_1046914::
	.incbin "sound/direct_sound_samples/1046914.bin"

	.align 2
DirectSoundWaveData_104698c::
	.incbin "sound/direct_sound_samples/104698c.bin"

	.align 2
DirectSoundWaveData_1047850::
	.incbin "sound/direct_sound_samples/1047850.bin"

	.align 2
DirectSoundWaveData_10480d0::
	.incbin "sound/direct_sound_samples/10480d0.bin"

	.align 2
DirectSoundWaveData_1048280::
	.incbin "sound/direct_sound_samples/1048280.bin"

	.align 2
DirectSoundWaveData_1048300::
	.incbin "sound/direct_sound_samples/1048300.bin"

	.align 2
DirectSoundWaveData_1048358::
	.incbin "sound/direct_sound_samples/1048358.bin"

	.align 2
DirectSoundWaveData_1048398::
	.incbin "sound/direct_sound_samples/1048398.bin"

	.align 2
DirectSoundWaveData_10483e0::
	.incbin "sound/direct_sound_samples/10483e0.bin"

	.align 2
DirectSoundWaveData_1048424::
	.incbin "sound/direct_sound_samples/1048424.bin"

	.align 2
DirectSoundWaveData_104844c::
	.incbin "sound/direct_sound_samples/104844c.bin"

	.align 2
DirectSoundWaveData_1048774::
	.incbin "sound/direct_sound_samples/1048774.bin"

	.align 2
DirectSoundWaveData_10489d4::
	.incbin "sound/direct_sound_samples/10489d4.bin"

	.align 2
DirectSoundWaveData_1049b5c::
	.incbin "sound/direct_sound_samples/1049b5c.bin"

	.align 2
DirectSoundWaveData_104abb4::
	.incbin "sound/direct_sound_samples/104abb4.bin"

	.align 2
DirectSoundWaveData_104b8d4::
	.incbin "sound/direct_sound_samples/104b8d4.bin"

	.align 2
DirectSoundWaveData_104c43c::
	.incbin "sound/direct_sound_samples/104c43c.bin"

	.align 2
DirectSoundWaveData_104cb60::
	.incbin "sound/direct_sound_samples/104cb60.bin"

	.align 2
DirectSoundWaveData_104cfb4::
	.incbin "sound/direct_sound_samples/104cfb4.bin"

	.align 2
DirectSoundWaveData_104d980::
	.incbin "sound/direct_sound_samples/104d980.bin"

	.align 2
DirectSoundWaveData_104fe24::
	.incbin "sound/direct_sound_samples/104fe24.bin"

	.align 2
DirectSoundWaveData_1051548::
	.incbin "sound/direct_sound_samples/1051548.bin"

	.align 2
DirectSoundWaveData_10528fc::
	.incbin "sound/direct_sound_samples/10528fc.bin"

	.align 2
DirectSoundWaveData_1053d20::
	.incbin "sound/direct_sound_samples/1053d20.bin"

	.align 2
DirectSoundWaveData_1000008::
	.incbin "sound/direct_sound_samples/1000008.bin"

	.align 2
DirectSoundWaveData_1054bfc::
	.incbin "sound/direct_sound_samples/1054bfc.bin"

	.align 2
DirectSoundWaveData_1055798::
	.incbin "sound/direct_sound_samples/1055798.bin"

	.align 2
DirectSoundWaveData_1057100::
	.incbin "sound/direct_sound_samples/1057100.bin"

	.align 2
DirectSoundWaveData_1058a0c::
	.incbin "sound/direct_sound_samples/1058a0c.bin"

	.align 2
DirectSoundWaveData_1059f70::
	.incbin "sound/direct_sound_samples/1059f70.bin"

	.align 2
DirectSoundWaveData_105b0c8::
	.incbin "sound/direct_sound_samples/105b0c8.bin"

	.align 2
DirectSoundWaveData_105c458::
	.incbin "sound/direct_sound_samples/105c458.bin"

	.align 2
DirectSoundWaveData_105d250::
	.incbin "sound/direct_sound_samples/105d250.bin"

	.align 2
DirectSoundWaveData_105e604::
	.incbin "sound/direct_sound_samples/105e604.bin"

	.align 2
DirectSoundWaveData_105f4d0::
	.incbin "sound/direct_sound_samples/105f4d0.bin"

	.align 2
DirectSoundWaveData_1060100::
	.incbin "sound/direct_sound_samples/1060100.bin"

	.align 2
DirectSoundWaveData_1060a40::
	.incbin "sound/direct_sound_samples/1060a40.bin"

	.align 2
DirectSoundWaveData_1061340::
	.incbin "sound/direct_sound_samples/1061340.bin"

	.align 2
DirectSoundWaveData_10618d4::
	.incbin "sound/direct_sound_samples/10618d4.bin"

	.align 2
DirectSoundWaveData_1061d18::
	.incbin "sound/direct_sound_samples/1061d18.bin"

	.align 2
DirectSoundWaveData_1061f28::
	.incbin "sound/direct_sound_samples/1061f28.bin"

	.align 2
DirectSoundWaveData_10631d0::
	.incbin "sound/direct_sound_samples/10631d0.bin"

	.align 2
DirectSoundWaveData_1064120::
	.incbin "sound/direct_sound_samples/1064120.bin"

	.align 2
DirectSoundWaveData_1064b5c::
	.incbin "sound/direct_sound_samples/1064b5c.bin"

	.align 2
DirectSoundWaveData_1065c74::
	.incbin "sound/direct_sound_samples/1065c74.bin"

	.align 2
DirectSoundWaveData_106619c::
	.incbin "sound/direct_sound_samples/106619c.bin"

	.align 2
DirectSoundWaveData_10666e4::
	.incbin "sound/direct_sound_samples/10666e4.bin"

	.align 2
DirectSoundWaveData_1066a98::
	.incbin "sound/direct_sound_samples/1066a98.bin"

	.align 2
DirectSoundWaveData_1066d4c::
	.incbin "sound/direct_sound_samples/1066d4c.bin"

	.align 2
DirectSoundWaveData_1066eec::
	.incbin "sound/direct_sound_samples/1066eec.bin"

	.align 2
DirectSoundWaveData_106705c::
	.incbin "sound/direct_sound_samples/106705c.bin"

	.align 2
DirectSoundWaveData_1067eb0::
	.incbin "sound/direct_sound_samples/1067eb0.bin"

	.align 2
DirectSoundWaveData_1068b94::
	.incbin "sound/direct_sound_samples/1068b94.bin"

	.align 2
DirectSoundWaveData_1069484::
	.incbin "sound/direct_sound_samples/1069484.bin"

	.align 2
DirectSoundWaveData_1069ba4::
	.incbin "sound/direct_sound_samples/1069ba4.bin"

	.align 2
DirectSoundWaveData_1069f60::
	.incbin "sound/direct_sound_samples/1069f60.bin"

	.align 2
DirectSoundWaveData_106a3d8::
	.incbin "sound/direct_sound_samples/106a3d8.bin"

	.align 2
DirectSoundWaveData_106a6b4::
	.incbin "sound/direct_sound_samples/106a6b4.bin"

	.align 2
DirectSoundWaveData_106a870::
	.incbin "sound/direct_sound_samples/106a870.bin"

	.align 2
DirectSoundWaveData_106aa84::
	.incbin "sound/direct_sound_samples/106aa84.bin"

	.align 2
DirectSoundWaveData_106adec::
	.incbin "sound/direct_sound_samples/106adec.bin"

	.align 2
DirectSoundWaveData_106b0c4::
	.incbin "sound/direct_sound_samples/106b0c4.bin"

	.align 2
DirectSoundWaveData_106d108::
	.incbin "sound/direct_sound_samples/106d108.bin"

	.align 2
DirectSoundWaveData_106ec68::
	.incbin "sound/direct_sound_samples/106ec68.bin"

	.align 2
DirectSoundWaveData_106f720::
	.incbin "sound/direct_sound_samples/106f720.bin"

	.align 2
DirectSoundWaveData_10701f8::
	.incbin "sound/direct_sound_samples/10701f8.bin"

	.align 2
DirectSoundWaveData_1070a90::
	.incbin "sound/direct_sound_samples/1070a90.bin"

	.align 2
DirectSoundWaveData_10715a8::
	.incbin "sound/direct_sound_samples/10715a8.bin"

	.align 2
DirectSoundWaveData_1071fbc::
	.incbin "sound/direct_sound_samples/1071fbc.bin"

	.align 2
DirectSoundWaveData_1072438::
	.incbin "sound/direct_sound_samples/1072438.bin"

	.align 2
DirectSoundWaveData_107404c::
	.incbin "sound/direct_sound_samples/107404c.bin"

	.align 2
DirectSoundWaveData_1075b14::
	.incbin "sound/direct_sound_samples/1075b14.bin"

	.align 2
DirectSoundWaveData_1076998::
	.incbin "sound/direct_sound_samples/1076998.bin"

	.align 2
DirectSoundWaveData_1078f58::
	.incbin "sound/direct_sound_samples/1078f58.bin"

	.align 2
DirectSoundWaveData_107a4f4::
	.incbin "sound/direct_sound_samples/107a4f4.bin"

	.align 2
DirectSoundWaveData_107af1c::
	.incbin "sound/direct_sound_samples/107af1c.bin"

	.align 2
DirectSoundWaveData_107cc28::
	.incbin "sound/direct_sound_samples/107cc28.bin"

	.align 2
DirectSoundWaveData_107e1a8::
	.incbin "sound/direct_sound_samples/107e1a8.bin"

	.align 2
DirectSoundWaveData_107e318::
	.incbin "sound/direct_sound_samples/107e318.bin"

	.align 2
DirectSoundWaveData_107ea30::
	.incbin "sound/direct_sound_samples/107ea30.bin"

	.align 2
DirectSoundWaveData_1082c30::
	.incbin "sound/direct_sound_samples/1082c30.bin"

	.align 2
DirectSoundWaveData_1083a80::
	.incbin "sound/direct_sound_samples/1083a80.bin"

	.align 2
DirectSoundWaveData_1084448::
	.incbin "sound/direct_sound_samples/1084448.bin"

	.align 2
DirectSoundWaveData_10849bc::
	.incbin "sound/direct_sound_samples/10849bc.bin"

	.align 2
DirectSoundWaveData_108707c::
	.incbin "sound/direct_sound_samples/108707c.bin"

	.align 2
DirectSoundWaveData_1087cb4::
	.incbin "sound/direct_sound_samples/1087cb4.bin"

	.align 2
DirectSoundWaveData_108887c::
	.incbin "sound/direct_sound_samples/108887c.bin"

	.align 2
DirectSoundWaveData_1088e34::
	.incbin "sound/direct_sound_samples/1088e34.bin"

	.align 2
DirectSoundWaveData_1089470::
	.incbin "sound/direct_sound_samples/1089470.bin"

	.align 2
DirectSoundWaveData_10899f8::
	.incbin "sound/direct_sound_samples/10899f8.bin"

	.align 2
DirectSoundWaveData_1089f50::
	.incbin "sound/direct_sound_samples/1089f50.bin"

	.align 2
DirectSoundWaveData_108a3e4::
	.incbin "sound/direct_sound_samples/108a3e4.bin"

	.align 2
DirectSoundWaveData_108a7b4::
	.incbin "sound/direct_sound_samples/108a7b4.bin"

	.align 2
DirectSoundWaveData_108ab60::
	.incbin "sound/direct_sound_samples/108ab60.bin"

	.align 2
DirectSoundWaveData_108ab84::
	.incbin "sound/direct_sound_samples/108ab84.bin"

	.align 2
DirectSoundWaveData_108ad30::
	.incbin "sound/direct_sound_samples/108ad30.bin"

	.align 2
DirectSoundWaveData_108b438::
	.incbin "sound/direct_sound_samples/108b438.bin"

	.align 2
DirectSoundWaveData_108b874::
	.incbin "sound/direct_sound_samples/108b874.bin"

	.align 2
DirectSoundWaveData_108bcd8::
	.incbin "sound/direct_sound_samples/108bcd8.bin"

	.align 2
DirectSoundWaveData_108c008::
	.incbin "sound/direct_sound_samples/108c008.bin"

	.align 2
DirectSoundWaveData_108c200::
	.incbin "sound/direct_sound_samples/108c200.bin"

	.align 2
DirectSoundWaveData_108cd78::
	.incbin "sound/direct_sound_samples/108cd78.bin"

	.align 2
DirectSoundWaveData_108d2e0::
	.incbin "sound/direct_sound_samples/108d2e0.bin"

	.align 2
DirectSoundWaveData_108d4f4::
	.incbin "sound/direct_sound_samples/108d4f4.bin"

	.align 2
DirectSoundWaveData_108fbf0::
	.incbin "sound/direct_sound_samples/108fbf0.bin"

	.align 2
DirectSoundWaveData_109289c::
	.incbin "sound/direct_sound_samples/109289c.bin"

	.align 2
DirectSoundWaveData_1094628::
	.incbin "sound/direct_sound_samples/1094628.bin"

	.align 2
DirectSoundWaveData_1094fe0::
	.incbin "sound/direct_sound_samples/1094fe0.bin"

	.align 2
DirectSoundWaveData_10952a0::
	.incbin "sound/direct_sound_samples/10952a0.bin"

	.align 2
DirectSoundWaveData_10961b4::
	.incbin "sound/direct_sound_samples/10961b4.bin"

	.align 2
DirectSoundWaveData_1096f48::
	.incbin "sound/direct_sound_samples/1096f48.bin"

	.align 2
DirectSoundWaveData_1099a38::
	.incbin "sound/direct_sound_samples/1099a38.bin"

	.align 2
DirectSoundWaveData_109c55c::
	.incbin "sound/direct_sound_samples/109c55c.bin"

	.align 2
DirectSoundWaveData_109eae4::
	.incbin "sound/direct_sound_samples/109eae4.bin"

	.align 2
DirectSoundWaveData_10a1b68::
	.incbin "sound/direct_sound_samples/10a1b68.bin"

	.align 2
DirectSoundWaveData_10a25e8::
	.incbin "sound/direct_sound_samples/10a25e8.bin"

	.align 2
DirectSoundWaveData_10a32b8::
	.incbin "sound/direct_sound_samples/10a32b8.bin"

	.align 2
DirectSoundWaveData_10a3f94::
	.incbin "sound/direct_sound_samples/10a3f94.bin"

	.align 2
DirectSoundWaveData_10a4924::
	.incbin "sound/direct_sound_samples/10a4924.bin"

	.align 2
DirectSoundWaveData_10a5e38::
	.incbin "sound/direct_sound_samples/10a5e38.bin"

	.align 2
DirectSoundWaveData_10a6480::
	.incbin "sound/direct_sound_samples/10a6480.bin"

	.align 2
DirectSoundWaveData_10a6d34::
	.incbin "sound/direct_sound_samples/10a6d34.bin"

	.align 2
DirectSoundWaveData_10a7894::
	.incbin "sound/direct_sound_samples/10a7894.bin"

	.align 2
DirectSoundWaveData_10a81e4::
	.incbin "sound/direct_sound_samples/10a81e4.bin"

	.align 2
DirectSoundWaveData_10a8770::
	.incbin "sound/direct_sound_samples/10a8770.bin"

	.align 2
DirectSoundWaveData_10a8c8c::
	.incbin "sound/direct_sound_samples/10a8c8c.bin"

	.align 2
DirectSoundWaveData_10a90b0::
	.incbin "sound/direct_sound_samples/10a90b0.bin"

	.align 2
DirectSoundWaveData_10a93b8::
	.incbin "sound/direct_sound_samples/10a93b8.bin"

	.align 2
DirectSoundWaveData_10a9614::
	.incbin "sound/direct_sound_samples/10a9614.bin"

	.align 2
DirectSoundWaveData_10a97f4::
	.incbin "sound/direct_sound_samples/10a97f4.bin"

	.align 2
DirectSoundWaveData_10a9fd0::
	.incbin "sound/direct_sound_samples/10a9fd0.bin"

	.align 2
DirectSoundWaveData_10aaa74::
	.incbin "sound/direct_sound_samples/10aaa74.bin"

	.align 2
DirectSoundWaveData_10ab0c8::
	.incbin "sound/direct_sound_samples/10ab0c8.bin"

	.align 2
DirectSoundWaveData_10ab490::
	.incbin "sound/direct_sound_samples/10ab490.bin"

	.align 2
DirectSoundWaveData_10ab67c::
	.incbin "sound/direct_sound_samples/10ab67c.bin"

	.align 2
DirectSoundWaveData_10abd04::
	.incbin "sound/direct_sound_samples/10abd04.bin"

	.align 2
DirectSoundWaveData_10ac1b0::
	.incbin "sound/direct_sound_samples/10ac1b0.bin"

	.align 2
DirectSoundWaveData_10ad218::
	.incbin "sound/direct_sound_samples/10ad218.bin"

	.align 2
DirectSoundWaveData_10adfd8::
	.incbin "sound/direct_sound_samples/10adfd8.bin"

	.align 2
DirectSoundWaveData_10aed10::
	.incbin "sound/direct_sound_samples/10aed10.bin"

	.align 2
DirectSoundWaveData_10004a8::
	.incbin "sound/direct_sound_samples/10004a8.bin"

	.align 2
DirectSoundWaveData_10af85c::
	.incbin "sound/direct_sound_samples/10af85c.bin"

	.align 2
DirectSoundWaveData_10b0f00::
	.incbin "sound/direct_sound_samples/10b0f00.bin"

	.align 2
DirectSoundWaveData_10b1f08::
	.incbin "sound/direct_sound_samples/10b1f08.bin"

	.align 2
DirectSoundWaveData_10b3c38::
	.incbin "sound/direct_sound_samples/10b3c38.bin"

	.align 2
DirectSoundWaveData_10b5c48::
	.incbin "sound/direct_sound_samples/10b5c48.bin"

	.align 2
DirectSoundWaveData_10b70c4::
	.incbin "sound/direct_sound_samples/10b70c4.bin"

	.align 2
DirectSoundWaveData_10b9014::
	.incbin "sound/direct_sound_samples/10b9014.bin"

	.align 2
DirectSoundWaveData_10ba7ac::
	.incbin "sound/direct_sound_samples/10ba7ac.bin"

	.align 2
DirectSoundWaveData_10bbf30::
	.incbin "sound/direct_sound_samples/10bbf30.bin"

	.align 2
DirectSoundWaveData_10bcf08::
	.incbin "sound/direct_sound_samples/10bcf08.bin"

	.align 2
DirectSoundWaveData_10bdaf4::
	.incbin "sound/direct_sound_samples/10bdaf4.bin"

	.align 2
DirectSoundWaveData_10c002c::
	.incbin "sound/direct_sound_samples/10c002c.bin"

	.align 2
DirectSoundWaveData_10c16b8::
	.incbin "sound/direct_sound_samples/10c16b8.bin"

	.align 2
DirectSoundWaveData_1001f2c::
	.incbin "sound/direct_sound_samples/1001f2c.bin"

	.align 2
DirectSoundWaveData_10c249c::
	.incbin "sound/direct_sound_samples/10c249c.bin"

	.align 2
DirectSoundWaveData_10c2c4c::
	.incbin "sound/direct_sound_samples/10c2c4c.bin"

	.align 2
DirectSoundWaveData_10c3168::
	.incbin "sound/direct_sound_samples/10c3168.bin"

	.align 2
DirectSoundWaveData_10c405c::
	.incbin "sound/direct_sound_samples/10c405c.bin"

	.align 2
DirectSoundWaveData_10c4d28::
	.incbin "sound/direct_sound_samples/10c4d28.bin"

	.align 2
DirectSoundWaveData_10c5638::
	.incbin "sound/direct_sound_samples/10c5638.bin"

	.align 2
DirectSoundWaveData_10c5824::
	.incbin "sound/direct_sound_samples/10c5824.bin"

	.align 2
DirectSoundWaveData_10c6268::
	.incbin "sound/direct_sound_samples/10c6268.bin"

	.align 2
DirectSoundWaveData_10c676c::
	.incbin "sound/direct_sound_samples/10c676c.bin"

	.align 2
DirectSoundWaveData_10c6c64::
	.incbin "sound/direct_sound_samples/10c6c64.bin"

	.align 2
DirectSoundWaveData_10c7124::
	.incbin "sound/direct_sound_samples/10c7124.bin"

	.align 2
DirectSoundWaveData_10c7420::
	.incbin "sound/direct_sound_samples/10c7420.bin"

	.align 2
DirectSoundWaveData_10c78d4::
	.incbin "sound/direct_sound_samples/10c78d4.bin"

	.align 2
DirectSoundWaveData_10c7bb8::
	.incbin "sound/direct_sound_samples/10c7bb8.bin"

	.align 2
DirectSoundWaveData_10c7d2c::
	.incbin "sound/direct_sound_samples/10c7d2c.bin"

	.align 2
DirectSoundWaveData_10c836c::
	.incbin "sound/direct_sound_samples/10c836c.bin"

	.align 2
DirectSoundWaveData_10c883c::
	.incbin "sound/direct_sound_samples/10c883c.bin"

	.align 2
DirectSoundWaveData_10c8c34::
	.incbin "sound/direct_sound_samples/10c8c34.bin"

	.align 2
DirectSoundWaveData_10c8f88::
	.incbin "sound/direct_sound_samples/10c8f88.bin"

	.align 2
DirectSoundWaveData_10c9390::
	.incbin "sound/direct_sound_samples/10c9390.bin"

	.align 2
DirectSoundWaveData_10c963c::
	.incbin "sound/direct_sound_samples/10c963c.bin"

	.align 2
DirectSoundWaveData_10c9890::
	.incbin "sound/direct_sound_samples/10c9890.bin"

	.align 2
DirectSoundWaveData_10c9a24::
	.incbin "sound/direct_sound_samples/10c9a24.bin"

	.align 2
DirectSoundWaveData_10c9d30::
	.incbin "sound/direct_sound_samples/10c9d30.bin"

	.align 2
DirectSoundWaveData_10c9fa0::
	.incbin "sound/direct_sound_samples/10c9fa0.bin"

	.align 2
DirectSoundWaveData_10ca248::
	.incbin "sound/direct_sound_samples/10ca248.bin"

	.align 2
DirectSoundWaveData_10ca330::
	.incbin "sound/direct_sound_samples/10ca330.bin"

	.align 2
DirectSoundWaveData_10ca38c::
	.incbin "sound/direct_sound_samples/10ca38c.bin"

	.align 2
DirectSoundWaveData_10cac64::
	.incbin "sound/direct_sound_samples/10cac64.bin"

	.align 2
DirectSoundWaveData_10cb2d4::
	.incbin "sound/direct_sound_samples/10cb2d4.bin"

	.align 2
DirectSoundWaveData_10cb930::
	.incbin "sound/direct_sound_samples/10cb930.bin"

	.align 2
DirectSoundWaveData_10cbccc::
	.incbin "sound/direct_sound_samples/10cbccc.bin"

	.align 2
DirectSoundWaveData_10cbdc0::
	.incbin "sound/direct_sound_samples/10cbdc0.bin"

	.align 2
DirectSoundWaveData_10cbeb4::
	.incbin "sound/direct_sound_samples/10cbeb4.bin"

	.align 2
DirectSoundWaveData_10cc274::
	.incbin "sound/direct_sound_samples/10cc274.bin"

	.align 2
DirectSoundWaveData_10cc60c::
	.incbin "sound/direct_sound_samples/10cc60c.bin"

	.align 2
DirectSoundWaveData_10cc8b8::
	.incbin "sound/direct_sound_samples/10cc8b8.bin"

	.align 2
DirectSoundWaveData_10ccbbc::
	.incbin "sound/direct_sound_samples/10ccbbc.bin"

	.align 2
DirectSoundWaveData_10cced4::
	.incbin "sound/direct_sound_samples/10cced4.bin"

	.align 2
DirectSoundWaveData_10ccfe4::
	.incbin "sound/direct_sound_samples/10ccfe4.bin"

	.align 2
DirectSoundWaveData_10cd0d8::
	.incbin "sound/direct_sound_samples/10cd0d8.bin"

	.align 2
DirectSoundWaveData_10cd174::
	.incbin "sound/direct_sound_samples/10cd174.bin"

	.align 2
DirectSoundWaveData_10cd1e4::
	.incbin "sound/direct_sound_samples/10cd1e4.bin"

	.align 2
DirectSoundWaveData_10cd23c::
	.incbin "sound/direct_sound_samples/10cd23c.bin"

	.align 2
DirectSoundWaveData_10cd288::
	.incbin "sound/direct_sound_samples/10cd288.bin"

	.align 2
DirectSoundWaveData_10cd748::
	.incbin "sound/direct_sound_samples/10cd748.bin"

	.align 2
DirectSoundWaveData_10cda0c::
	.incbin "sound/direct_sound_samples/10cda0c.bin"

	.align 2
DirectSoundWaveData_10ce568::
	.incbin "sound/direct_sound_samples/10ce568.bin"

	.align 2
DirectSoundWaveData_10ced3c::
	.incbin "sound/direct_sound_samples/10ced3c.bin"

	.align 2
DirectSoundWaveData_10cf53c::
	.incbin "sound/direct_sound_samples/10cf53c.bin"

	.align 2
DirectSoundWaveData_10cfc6c::
	.incbin "sound/direct_sound_samples/10cfc6c.bin"

	.align 2
DirectSoundWaveData_10d018c::
	.incbin "sound/direct_sound_samples/10d018c.bin"

	.align 2
DirectSoundWaveData_10d05bc::
	.incbin "sound/direct_sound_samples/10d05bc.bin"

	.align 2
DirectSoundWaveData_10d0884::
	.incbin "sound/direct_sound_samples/10d0884.bin"

	.align 2
DirectSoundWaveData_10d0c78::
	.incbin "sound/direct_sound_samples/10d0c78.bin"

	.align 2
DirectSoundWaveData_10d10b8::
	.incbin "sound/direct_sound_samples/10d10b8.bin"

	.align 2
DirectSoundWaveData_10d13c0::
	.incbin "sound/direct_sound_samples/10d13c0.bin"

	.align 2
DirectSoundWaveData_10d1514::
	.incbin "sound/direct_sound_samples/10d1514.bin"

	.align 2
DirectSoundWaveData_10d15f4::
	.incbin "sound/direct_sound_samples/10d15f4.bin"

	.align 2
DirectSoundWaveData_10d250c::
	.incbin "sound/direct_sound_samples/10d250c.bin"

	.align 2
DirectSoundWaveData_10d2d08::
	.incbin "sound/direct_sound_samples/10d2d08.bin"

	.align 2
DirectSoundWaveData_10d310c::
	.incbin "sound/direct_sound_samples/10d310c.bin"

	.align 2
DirectSoundWaveData_10d4824::
	.incbin "sound/direct_sound_samples/10d4824.bin"

	.align 2
DirectSoundWaveData_10d5b2c::
	.incbin "sound/direct_sound_samples/10d5b2c.bin"

	.align 2
DirectSoundWaveData_10d6cd4::
	.incbin "sound/direct_sound_samples/10d6cd4.bin"

	.align 2
DirectSoundWaveData_10d6dd0::
	.incbin "sound/direct_sound_samples/10d6dd0.bin"

	.align 2
DirectSoundWaveData_10d6e58::
	.incbin "sound/direct_sound_samples/10d6e58.bin"

	.align 2
DirectSoundWaveData_10d6ea4::
	.incbin "sound/direct_sound_samples/10d6ea4.bin"

	.align 2
DirectSoundWaveData_10d7aec::
	.incbin "sound/direct_sound_samples/10d7aec.bin"

	.align 2
DirectSoundWaveData_10d8528::
	.incbin "sound/direct_sound_samples/10d8528.bin"

	.align 2
DirectSoundWaveData_10d9cc0::
	.incbin "sound/direct_sound_samples/10d9cc0.bin"

	.align 2
DirectSoundWaveData_10dbba8::
	.incbin "sound/direct_sound_samples/10dbba8.bin"

	.align 2
DirectSoundWaveData_10dd938::
	.incbin "sound/direct_sound_samples/10dd938.bin"

	.align 2
DirectSoundWaveData_10df474::
	.incbin "sound/direct_sound_samples/10df474.bin"

	.align 2
DirectSoundWaveData_10e0f2c::
	.incbin "sound/direct_sound_samples/10e0f2c.bin"

	.align 2
DirectSoundWaveData_10e1984::
	.incbin "sound/direct_sound_samples/10e1984.bin"

	.align 2
DirectSoundWaveData_10e5520::
	.incbin "sound/direct_sound_samples/10e5520.bin"

	.align 2
DirectSoundWaveData_10e7d78::
	.incbin "sound/direct_sound_samples/10e7d78.bin"

	.align 2
DirectSoundWaveData_10ea4ac::
	.incbin "sound/direct_sound_samples/10ea4ac.bin"

	.align 2
DirectSoundWaveData_10ebac0::
	.incbin "sound/direct_sound_samples/10ebac0.bin"

	.align 2
DirectSoundWaveData_10ed380::
	.incbin "sound/direct_sound_samples/10ed380.bin"

	.align 2
DirectSoundWaveData_10ee964::
	.incbin "sound/direct_sound_samples/10ee964.bin"

	.align 2
DirectSoundWaveData_10f00a4::
	.incbin "sound/direct_sound_samples/10f00a4.bin"

	.align 2
DirectSoundWaveData_10f18ac::
	.incbin "sound/direct_sound_samples/10f18ac.bin"

	.align 2
DirectSoundWaveData_10f255c::
	.incbin "sound/direct_sound_samples/10f255c.bin"

	.align 2
DirectSoundWaveData_1005b5c::
	.incbin "sound/direct_sound_samples/1005b5c.bin"

	.align 2
DirectSoundWaveData_10f3204::
	.incbin "sound/direct_sound_samples/10f3204.bin"

	.align 2
DirectSoundWaveData_10f5014::
	.incbin "sound/direct_sound_samples/10f5014.bin"

	.align 2
DirectSoundWaveData_10f5f60::
	.incbin "sound/direct_sound_samples/10f5f60.bin"

	.align 2
DirectSoundWaveData_10f6ca8::
	.incbin "sound/direct_sound_samples/10f6ca8.bin"

	.align 2
DirectSoundWaveData_10f76e0::
	.incbin "sound/direct_sound_samples/10f76e0.bin"

	.align 2
DirectSoundWaveData_10f8030::
	.incbin "sound/direct_sound_samples/10f8030.bin"

	.align 2
DirectSoundWaveData_10f959c::
	.incbin "sound/direct_sound_samples/10f959c.bin"

	.align 2
DirectSoundWaveData_10fa228::
	.incbin "sound/direct_sound_samples/10fa228.bin"

	.align 2
DirectSoundWaveData_10fb8cc::
	.incbin "sound/direct_sound_samples/10fb8cc.bin"

	.align 2
DirectSoundWaveData_10fc5a0::
	.incbin "sound/direct_sound_samples/10fc5a0.bin"

	.align 2
DirectSoundWaveData_10fdf28::
	.incbin "sound/direct_sound_samples/10fdf28.bin"

	.align 2
DirectSoundWaveData_10ff5e0::
	.incbin "sound/direct_sound_samples/10ff5e0.bin"

	.align 2
DirectSoundWaveData_11008b4::
	.incbin "sound/direct_sound_samples/11008b4.bin"

	.align 2
DirectSoundWaveData_1101b14::
	.incbin "sound/direct_sound_samples/1101b14.bin"

	.align 2
DirectSoundWaveData_1102900::
	.incbin "sound/direct_sound_samples/1102900.bin"

	.align 2
DirectSoundWaveData_1103ba4::
	.incbin "sound/direct_sound_samples/1103ba4.bin"

	.align 2
DirectSoundWaveData_11069c0::
	.incbin "sound/direct_sound_samples/11069c0.bin"

	.align 2
DirectSoundWaveData_1108ee8::
	.incbin "sound/direct_sound_samples/1108ee8.bin"

	.align 2
DirectSoundWaveData_1109558::
	.incbin "sound/direct_sound_samples/1109558.bin"

	.align 2
DirectSoundWaveData_110a954::
	.incbin "sound/direct_sound_samples/110a954.bin"

	.align 2
DirectSoundWaveData_110b5e4::
	.incbin "sound/direct_sound_samples/110b5e4.bin"

	.align 2
DirectSoundWaveData_110c7f0::
	.incbin "sound/direct_sound_samples/110c7f0.bin"

	.align 2
DirectSoundWaveData_110d1e0::
	.incbin "sound/direct_sound_samples/110d1e0.bin"

	.align 2
DirectSoundWaveData_110d41c::
	.incbin "sound/direct_sound_samples/110d41c.bin"

	.align 2
DirectSoundWaveData_110d60c::
	.incbin "sound/direct_sound_samples/110d60c.bin"

	.align 2
DirectSoundWaveData_110d78c::
	.incbin "sound/direct_sound_samples/110d78c.bin"

	.align 2
DirectSoundWaveData_110db9c::
	.incbin "sound/direct_sound_samples/110db9c.bin"

	.align 2
DirectSoundWaveData_110df98::
	.incbin "sound/direct_sound_samples/110df98.bin"

	.align 2
DirectSoundWaveData_110e238::
	.incbin "sound/direct_sound_samples/110e238.bin"

	.align 2
DirectSoundWaveData_110e6dc::
	.incbin "sound/direct_sound_samples/110e6dc.bin"

	.align 2
DirectSoundWaveData_110ea48::
	.incbin "sound/direct_sound_samples/110ea48.bin"

	.align 2
DirectSoundWaveData_110ed7c::
	.incbin "sound/direct_sound_samples/110ed7c.bin"

	.align 2
DirectSoundWaveData_110eefc::
	.incbin "sound/direct_sound_samples/110eefc.bin"

	.align 2
DirectSoundWaveData_110f640::
	.incbin "sound/direct_sound_samples/110f640.bin"

	.align 2
DirectSoundWaveData_110fb98::
	.incbin "sound/direct_sound_samples/110fb98.bin"

	.align 2
DirectSoundWaveData_1110180::
	.incbin "sound/direct_sound_samples/1110180.bin"

	.align 2
DirectSoundWaveData_1110fe0::
	.incbin "sound/direct_sound_samples/1110fe0.bin"

	.align 2
DirectSoundWaveData_1111ad0::
	.incbin "sound/direct_sound_samples/1111ad0.bin"

	.align 2
DirectSoundWaveData_1112204::
	.incbin "sound/direct_sound_samples/1112204.bin"

	.align 2
DirectSoundWaveData_11129b4::
	.incbin "sound/direct_sound_samples/11129b4.bin"

	.align 2
DirectSoundWaveData_1112ccc::
	.incbin "sound/direct_sound_samples/1112ccc.bin"

	.align 2
DirectSoundWaveData_1113910::
	.incbin "sound/direct_sound_samples/1113910.bin"

	.align 2
DirectSoundWaveData_1114018::
	.incbin "sound/direct_sound_samples/1114018.bin"

	.align 2
DirectSoundWaveData_111439c::
	.incbin "sound/direct_sound_samples/111439c.bin"

	.align 2
DirectSoundWaveData_111451c::
	.incbin "sound/direct_sound_samples/111451c.bin"

	.align 2
DirectSoundWaveData_11147b0::
	.incbin "sound/direct_sound_samples/11147b0.bin"

	.align 2
DirectSoundWaveData_11152f4::
	.incbin "sound/direct_sound_samples/11152f4.bin"

	.align 2
DirectSoundWaveData_11158f4::
	.incbin "sound/direct_sound_samples/11158f4.bin"

	.align 2
DirectSoundWaveData_111602c::
	.incbin "sound/direct_sound_samples/111602c.bin"

	.align 2
DirectSoundWaveData_1007514::
	.incbin "sound/direct_sound_samples/1007514.bin"

	.align 2
DirectSoundWaveData_1116654::
	.incbin "sound/direct_sound_samples/1116654.bin"

	.align 2
DirectSoundWaveData_11166a8::
	.incbin "sound/direct_sound_samples/11166a8.bin"

	.align 2
DirectSoundWaveData_1116b6c::
	.incbin "sound/direct_sound_samples/1116b6c.bin"

	.align 2
DirectSoundWaveData_1116eec::
	.incbin "sound/direct_sound_samples/1116eec.bin"

	.align 2
DirectSoundWaveData_1117308::
	.incbin "sound/direct_sound_samples/1117308.bin"

	.align 2
DirectSoundWaveData_1117cbc::
	.incbin "sound/direct_sound_samples/1117cbc.bin"

	.align 2
DirectSoundWaveData_1118d84::
	.incbin "sound/direct_sound_samples/1118d84.bin"

	.align 2
DirectSoundWaveData_1119710::
	.incbin "sound/direct_sound_samples/1119710.bin"

	.align 2
DirectSoundWaveData_100aeac::
	.incbin "sound/direct_sound_samples/100aeac.bin"

	.align 2
DirectSoundWaveData_111a2b0::
	.incbin "sound/direct_sound_samples/111a2b0.bin"

	.align 2
DirectSoundWaveData_111a804::
	.incbin "sound/direct_sound_samples/111a804.bin"

	.align 2
DirectSoundWaveData_100cbb8::
	.incbin "sound/direct_sound_samples/100cbb8.bin"

	.align 2
DirectSoundWaveData_111cd78::
	.incbin "sound/direct_sound_samples/111cd78.bin"

	.align 2
DirectSoundWaveData_111f0cc::
	.incbin "sound/direct_sound_samples/111f0cc.bin"

	.align 2
DirectSoundWaveData_1121470::
	.incbin "sound/direct_sound_samples/1121470.bin"

	.align 2
DirectSoundWaveData_112376c::
	.incbin "sound/direct_sound_samples/112376c.bin"

	.align 2
DirectSoundWaveData_1124010::
	.incbin "sound/direct_sound_samples/1124010.bin"

	.align 2
DirectSoundWaveData_1124864::
	.incbin "sound/direct_sound_samples/1124864.bin"

	.align 2
DirectSoundWaveData_1125848::
	.incbin "sound/direct_sound_samples/1125848.bin"

	.align 2
DirectSoundWaveData_1125d98::
	.incbin "sound/direct_sound_samples/1125d98.bin"

	.align 2
DirectSoundWaveData_1126694::
	.incbin "sound/direct_sound_samples/1126694.bin"

	.align 2
DirectSoundWaveData_1126920::
	.incbin "sound/direct_sound_samples/1126920.bin"

	.align 2
DirectSoundWaveData_1127414::
	.incbin "sound/direct_sound_samples/1127414.bin"

	.align 2
DirectSoundWaveData_1008e98::
	.incbin "sound/direct_sound_samples/1008e98.bin"

	.align 2
DirectSoundWaveData_11283a0::
	.incbin "sound/direct_sound_samples/11283a0.bin"

	.align 2
DirectSoundWaveData_1128804::
	.incbin "sound/direct_sound_samples/1128804.bin"

	.align 2
DirectSoundWaveData_1128ca4::
	.incbin "sound/direct_sound_samples/1128ca4.bin"

	.align 2
DirectSoundWaveData_1129404::
	.incbin "sound/direct_sound_samples/1129404.bin"

	.align 2
DirectSoundWaveData_112b29c::
	.incbin "sound/direct_sound_samples/112b29c.bin"

	.align 2
DirectSoundWaveData_112b558::
	.incbin "sound/direct_sound_samples/112b558.bin"

	.align 2
DirectSoundWaveData_112c684::
	.incbin "sound/direct_sound_samples/112c684.bin"

	.align 2
DirectSoundWaveData_10094ac::
	.incbin "sound/direct_sound_samples/10094ac.bin"

	.align 2
DirectSoundWaveData_112c81c::
	.incbin "sound/direct_sound_samples/112c81c.bin"

	.align 2
DirectSoundWaveData_112d01c::
	.incbin "sound/direct_sound_samples/112d01c.bin"

	.align 2
DirectSoundWaveData_112d9d8::
	.incbin "sound/direct_sound_samples/112d9d8.bin"

	.align 2
DirectSoundWaveData_112e0ec::
	.incbin "sound/direct_sound_samples/112e0ec.bin"

	.align 2
DirectSoundWaveData_112e448::
	.incbin "sound/direct_sound_samples/112e448.bin"

	.align 2
DirectSoundWaveData_112fa10::
	.incbin "sound/direct_sound_samples/112fa10.bin"

	.align 2
DirectSoundWaveData_11307fc::
	.incbin "sound/direct_sound_samples/11307fc.bin"

	.align 2
DirectSoundWaveData_1009b80::
	.incbin "sound/direct_sound_samples/1009b80.bin"

	.align 2
DirectSoundWaveData_1008da0::
	.incbin "sound/direct_sound_samples/1008da0.bin"

	.align 2
DirectSoundWaveData_100c800::
	.incbin "sound/direct_sound_samples/100c800.bin"

	.align 2
DirectSoundWaveData_100ec2c::
	.incbin "sound/direct_sound_samples/100ec2c.bin"

	.align 2
DirectSoundWaveData_100f5f8::
	.incbin "sound/direct_sound_samples/100f5f8.bin"

	.align 2
DirectSoundWaveData_1012b70::
	.incbin "sound/direct_sound_samples/1012b70.bin"

	.align 2
DirectSoundWaveData_1013b38::
	.incbin "sound/direct_sound_samples/1013b38.bin"

	.align 2
DirectSoundWaveData_1014134::
	.incbin "sound/direct_sound_samples/1014134.bin"

	.align 2
DirectSoundWaveData_1138d70::
	.incbin "sound/direct_sound_samples/1138d70.bin"

	.align 2
DirectSoundWaveData_113a240::
	.incbin "sound/direct_sound_samples/113a240.bin"

	.align 2
DirectSoundWaveData_113b690::
	.incbin "sound/direct_sound_samples/113b690.bin"

	.align 2
DirectSoundWaveData_113cf71::
	.incbin "sound/direct_sound_samples/113cf71.bin"

	.align 2
DirectSoundWaveData_113dec9::
	.incbin "sound/direct_sound_samples/113dec9.bin"

	.align 2
DirectSoundWaveData_113ec21::
	.incbin "sound/direct_sound_samples/113ec21.bin"

	.align 2
DirectSoundWaveData_113fb69::
	.incbin "sound/direct_sound_samples/113fb69.bin"

	.align 2
DirectSoundWaveData_1141201::
	.incbin "sound/direct_sound_samples/1141201.bin"

	.align 2
DirectSoundWaveData_11420c9::
	.incbin "sound/direct_sound_samples/11420c9.bin"

	.align 2
DirectSoundWaveData_11432d9::
	.incbin "sound/direct_sound_samples/11432d9.bin"

	.align 2
DirectSoundWaveData_11441a1::
	.incbin "sound/direct_sound_samples/11441a1.bin"

	.align 2
DirectSoundWaveData_1144ec9::
	.incbin "sound/direct_sound_samples/1144ec9.bin"

	.align 2
DirectSoundWaveData_1145b01::
	.incbin "sound/direct_sound_samples/1145b01.bin"

	.align 2
DirectSoundWaveData_1147109::
	.incbin "sound/direct_sound_samples/1147109.bin"

	.align 2
DirectSoundWaveData_1148c01::
	.incbin "sound/direct_sound_samples/1148c01.bin"

	.align 2
DirectSoundWaveData_114a381::
	.incbin "sound/direct_sound_samples/114a381.bin"

	.align 2
DirectSoundWaveData_114b4c9::
	.incbin "sound/direct_sound_samples/114b4c9.bin"

	.align 2
DirectSoundWaveData_114d0a1::
	.incbin "sound/direct_sound_samples/114d0a1.bin"

	.align 2
DirectSoundWaveData_114ec09::
	.incbin "sound/direct_sound_samples/114ec09.bin"

	.align 2
DirectSoundWaveData_114ffc9::
	.incbin "sound/direct_sound_samples/114ffc9.bin"

	.align 2
DirectSoundWaveData_1151961::
	.incbin "sound/direct_sound_samples/1151961.bin"

	.align 2
DirectSoundWaveData_1152d19::
	.incbin "sound/direct_sound_samples/1152d19.bin"

	.align 2
DirectSoundWaveData_11542e9::
	.incbin "sound/direct_sound_samples/11542e9.bin"

	.align 2
DirectSoundWaveData_11555b1::
	.incbin "sound/direct_sound_samples/11555b1.bin"

	.align 2
DirectSoundWaveData_1156b91::
	.incbin "sound/direct_sound_samples/1156b91.bin"

	.align 2
DirectSoundWaveData_11584b9::
	.incbin "sound/direct_sound_samples/11584b9.bin"

	.align 2
DirectSoundWaveData_1159769::
	.incbin "sound/direct_sound_samples/1159769.bin"

	.align 2
DirectSoundWaveData_115aa51::
	.incbin "sound/direct_sound_samples/115aa51.bin"

	.align 2
DirectSoundWaveData_115c021::
	.incbin "sound/direct_sound_samples/115c021.bin"

	.align 2
DirectSoundWaveData_115caa1::
	.incbin "sound/direct_sound_samples/115caa1.bin"

	.align 2
DirectSoundWaveData_115e1a1::
	.incbin "sound/direct_sound_samples/115e1a1.bin"

	.align 2
DirectSoundWaveData_115f8a1::
	.incbin "sound/direct_sound_samples/115f8a1.bin"

	.align 2
DirectSoundWaveData_1160191::
	.incbin "sound/direct_sound_samples/1160191.bin"

	.align 2
DirectSoundWaveData_1160d79::
	.incbin "sound/direct_sound_samples/1160d79.bin"

	.align 2
DirectSoundWaveData_1161961::
	.incbin "sound/direct_sound_samples/1161961.bin"

	.align 2
DirectSoundWaveData_1162251::
	.incbin "sound/direct_sound_samples/1162251.bin"

	.align 2
DirectSoundWaveData_1162e39::
	.incbin "sound/direct_sound_samples/1162e39.bin"

	.align 2
DirectSoundWaveData_1163d89::
	.incbin "sound/direct_sound_samples/1163d89.bin"

	.align 2
DirectSoundWaveData_1164cd9::
	.incbin "sound/direct_sound_samples/1164cd9.bin"

	.align 2
DirectSoundWaveData_1165b49::
	.incbin "sound/direct_sound_samples/1165b49.bin"

	.align 2
altosax72::
	.incbin "sound/direct_sound_samples/altosax72.bin"

	.align 2
ridecymbal::
	.incbin "sound/direct_sound_samples/ridecymbal.bin"
	
	.align 2
eggshaker::
	.incbin "sound/direct_sound_samples/eggshaker.bin"

	.align 2
marimba60::
	.incbin "sound/direct_sound_samples/marimba60.bin"

	.align 2
orchestrahit72::
	.incbin "sound/direct_sound_samples/orchestrahit72.bin"

