@ Voicegroup para la Wild Battle de BW2
@ Usa los instrumentos de GBA para ajustarse a los de BW según la lista de
@ https://github.com/LukeZGD/B2W2-Music-Patch/blob/master/txt%20info/bw%20voicegroup%20instruments.txt
@ Incluye un voicegroup de percusión
@ Tiene los instrumentos justos para la música de wild battle;
@ si se desea completar puede usarse tanto la lista anterior como el voicegroup 1.5 Set 2 en
@ https://github.com/LukeZGD/B2W2-Music-Patch/blob/master/Soundfonts%20B2W2%20Music%20Patch.zip
	.align 2
voicegroup500:: @ 8699854
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_glockenspiel, 255, 204, 51, 242
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_synth_bass, 255, 252, 0, 146
	voice_keysplit voicegroup006, KeySplitTable2
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup009, KeySplitTable5
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_pizzicato_strings, 255, 216, 0, 165
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_harp, 255, 242, 51, 242
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup008, KeySplitTable4
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88_timpani, 255, 246, 0, 226
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup007, KeySplitTable3
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_keysplit_all voicegroup500drums
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_noise_alt 0, 0, 2, 6, 2
	voice_noise_alt 0, 0, 1, 6, 0

	.align 2
voicegroup500drums:: @ 8676148
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_drum_and_percussion_kick, 255, 0, 255, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sd90_solo_snare, 255, 180, 175, 228
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound_no_resample 64, 80, DirectSoundWaveData_sc88_orchestra_snare, 255, 0, 255, 242  @ 8676340
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88_standard3_snare, 255, 0, 255, 242  @ 8676370
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound_no_resample 64, 29, DirectSoundWaveData_sc88_orchestra_cymbal_crash, 255, 235, 0, 231
	voice_directsound 63, 64, DirectSoundWaveData_sc88_orchestra_cymbal_crash, 255, 235, 0, 231