
	.align 2
voicegroup191:: @ 1188000
	voice_keysplit voicegroup192, KeySplitTable6
	voice_keysplit voicegroup193, KeySplitTable6
	voice_keysplit voicegroup194, KeySplitTable6
	voice_keysplit voicegroup195, KeySplitTable7
	voice_keysplit voicegroup196, KeySplitTable8
	voice_keysplit voicegroup197, KeySplitTable9
	voice_keysplit voicegroup198, KeySplitTable10
	voice_keysplit voicegroup199, KeySplitTable7
	voice_keysplit voicegroup200, KeySplitTable11
	voice_keysplit voicegroup201, KeySplitTable12
	voice_keysplit voicegroup202, KeySplitTable11
	voice_keysplit voicegroup203, KeySplitTable13
	voice_keysplit voicegroup204, KeySplitTable14
	voice_keysplit voicegroup205, KeySplitTable15
	voice_directsound 60, 0, DirectSoundWaveData_1000008, 255, 249, 0, 235
	voice_keysplit voicegroup206, KeySplitTable16
	voice_keysplit voicegroup207, KeySplitTable17
	voice_keysplit voicegroup208, KeySplitTable17
	voice_keysplit voicegroup209, KeySplitTable17
	voice_keysplit voicegroup210, KeySplitTable13
	voice_keysplit voicegroup211, KeySplitTable17
	voice_keysplit voicegroup212, KeySplitTable18
	voice_keysplit voicegroup213, KeySplitTable19
	voice_keysplit voicegroup214, KeySplitTable10
	voice_keysplit voicegroup215, KeySplitTable9
	voice_keysplit voicegroup216, KeySplitTable19
	voice_keysplit voicegroup217, KeySplitTable9
	voice_keysplit voicegroup218, KeySplitTable19
	voice_keysplit voicegroup219, KeySplitTable20
	voice_keysplit voicegroup220, KeySplitTable21
	voice_keysplit voicegroup221, KeySplitTable22
	voice_keysplit voicegroup222, KeySplitTable16
	voice_keysplit voicegroup223, KeySplitTable13
	voice_keysplit voicegroup224, KeySplitTable10
	voice_keysplit voicegroup225, KeySplitTable20
	voice_keysplit voicegroup226, KeySplitTable20
	voice_keysplit voicegroup227, KeySplitTable23
	voice_keysplit voicegroup228, KeySplitTable23
	voice_keysplit voicegroup229, KeySplitTable23
	voice_keysplit voicegroup230, KeySplitTable24
	voice_keysplit voicegroup231, KeySplitTable22
	voice_keysplit voicegroup232, KeySplitTable22
	voice_keysplit voicegroup233, KeySplitTable25
	voice_keysplit voicegroup234, KeySplitTable25
	voice_keysplit voicegroup235, KeySplitTable12
	voice_keysplit voicegroup236, KeySplitTable16
	voice_keysplit voicegroup237, KeySplitTable24
	voice_directsound 60, 0, DirectSoundWaveData_10004a8, 255, 0, 255, 235
	voice_keysplit voicegroup238, KeySplitTable12
	voice_keysplit voicegroup239, KeySplitTable12
	voice_keysplit voicegroup240, KeySplitTable18
	voice_keysplit voicegroup241, KeySplitTable18
	voice_keysplit voicegroup242, KeySplitTable16
	voice_keysplit voicegroup243, KeySplitTable24
	voice_keysplit voicegroup244, KeySplitTable11
	voice_directsound 60, 0, DirectSoundWaveData_1001f2c, 255, 253, 0, 235
	voice_keysplit voicegroup245, KeySplitTable21
	voice_keysplit voicegroup246, KeySplitTable21
	voice_keysplit voicegroup247, KeySplitTable26
	voice_keysplit voicegroup248, KeySplitTable27
	voice_keysplit voicegroup249, KeySplitTable28
	voice_keysplit voicegroup250, KeySplitTable28
	voice_keysplit voicegroup251, KeySplitTable19
	voice_keysplit voicegroup252, KeySplitTable29
	voice_keysplit voicegroup253, KeySplitTable27
	voice_keysplit voicegroup254, KeySplitTable25
	voice_keysplit voicegroup255, KeySplitTable26
	voice_keysplit voicegroup256, KeySplitTable19
	voice_keysplit voicegroup257, KeySplitTable20
	voice_keysplit voicegroup258, KeySplitTable27
	voice_keysplit voicegroup259, KeySplitTable29
	voice_keysplit voicegroup260, KeySplitTable30
	voice_keysplit voicegroup261, KeySplitTable11
	voice_keysplit voicegroup262, KeySplitTable27
	voice_keysplit voicegroup263, KeySplitTable30
	voice_keysplit voicegroup264, KeySplitTable31
	voice_keysplit voicegroup265, KeySplitTable31
	voice_keysplit voicegroup266, KeySplitTable13
	voice_keysplit voicegroup267, KeySplitTable7
	voice_keysplit voicegroup268, KeySplitTable14
	voice_keysplit voicegroup269, KeySplitTable30
	voice_keysplit voicegroup270, KeySplitTable7
	voice_keysplit voicegroup271, KeySplitTable14
	voice_keysplit voicegroup272, KeySplitTable32
	voice_keysplit voicegroup273, KeySplitTable15
	voice_keysplit voicegroup274, KeySplitTable33
	voice_keysplit voicegroup275, KeySplitTable34
	voice_keysplit voicegroup276, KeySplitTable14
	voice_keysplit voicegroup277, KeySplitTable28
	voice_keysplit voicegroup278, KeySplitTable33
	voice_keysplit voicegroup279, KeySplitTable8
	voice_directsound 60, 0, DirectSoundWaveData_1005b5c, 255, 0, 255, 235
	voice_keysplit voicegroup280, KeySplitTable8
	voice_keysplit voicegroup281, KeySplitTable7
	voice_keysplit voicegroup282, KeySplitTable15
	voice_keysplit voicegroup283, KeySplitTable18
	voice_keysplit voicegroup284, KeySplitTable31
	voice_keysplit voicegroup285, KeySplitTable33
	voice_keysplit voicegroup286, KeySplitTable33
	voice_keysplit voicegroup287, KeySplitTable34
	voice_keysplit voicegroup288, KeySplitTable34
	voice_directsound 60, 0, DirectSoundWaveData_1007514, 255, 0, 255, 235
	voice_keysplit voicegroup289, KeySplitTable15
	voice_keysplit voicegroup290, KeySplitTable32
	voice_keysplit voicegroup291, KeySplitTable31
	voice_keysplit voicegroup292, KeySplitTable35
	voice_keysplit voicegroup293, KeySplitTable35
	voice_keysplit voicegroup294, KeySplitTable29
	voice_keysplit voicegroup295, KeySplitTable31
	voice_keysplit voicegroup296, KeySplitTable30
	voice_keysplit voicegroup297, KeySplitTable25
	voice_keysplit voicegroup298, KeySplitTable35
	voice_directsound 60, 0, DirectSoundWaveData_1008da0, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1008e98, 255, 242, 0, 235
	voice_keysplit voicegroup299, KeySplitTable34
	voice_directsound 60, 0, DirectSoundWaveData_10094ac, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1009b80, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_100aeac, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_100c800, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_100cbb8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_100ec2c, 255, 0, 255, 235
	voice_keysplit voicegroup300, KeySplitTable32
	voice_directsound 60, 0, DirectSoundWaveData_100f5f8, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1012b70, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1013b38, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1014134, 255, 0, 255, 235
	voice_keysplit_all voicegroup301
	voice_keysplit_all voicegroup302
