
	.align 2
voicegroup298:: @ 1134f28
	voice_directsound 60, 0, DirectSoundWaveData_1110fe0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1111ad0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1111ad0, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1112204, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1112204, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_11129b4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_11129b4, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1048424, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1048424, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1048424, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1112ccc, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1112ccc, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1112ccc, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1112ccc, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_10701f8, 255, 252, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_1113910, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1113910, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1113910, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1114018, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_1114018, 255, 0, 255, 235
	voice_directsound 60, 0, DirectSoundWaveData_111439c, 255, 0, 255, 235
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_111451c, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_11147b0, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_11152f4, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_11158f4, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_111602c, 255, 0, 255, 245
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_1116654, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_11166a8, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_1116b6c, 255, 235, 0, 204
	voice_directsound 60, 0, DirectSoundWaveData_1116eec, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_1117308, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_1117cbc, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_1118d84, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_1119710, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_100aeac, 255, 235, 0, 235
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_111a2b0, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_111a804, 255, 250, 0, 249
	voice_directsound 60, 0, DirectSoundWaveData_100cbb8, 255, 250, 0, 249
	voice_directsound 60, 0, DirectSoundWaveData_111cd78, 255, 242, 0, 249
	voice_directsound 60, 0, DirectSoundWaveData_111f0cc, 255, 249, 0, 249
	voice_directsound 60, 0, DirectSoundWaveData_1121470, 255, 242, 0, 249
	voice_directsound 60, 0, DirectSoundWaveData_112376c, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_1124010, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_1124864, 255, 242, 0, 242
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_1125848, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_1125d98, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_1126694, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_1126920, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_1127414, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_1008e98, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_11283a0, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_1128804, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_1128ca4, 255, 0, 255, 245
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_1129404, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_112b29c, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_112b558, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_112c684, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_10094ac, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_112c81c, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_112d01c, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_112d9d8, 255, 242, 0, 242
	voice_directsound 60, 0, DirectSoundWaveData_112e0ec, 255, 0, 255, 245
	voice_square_1 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_112e448, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_112fa10, 255, 235, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_11307fc, 255, 0, 255, 245
	voice_directsound 60, 0, DirectSoundWaveData_1009b80, 255, 235, 0, 235
	voice_directsound 60, 0, DirectSoundWaveData_111451c, 8, 0, 0, 0
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Unkown voice entry type: 51
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Unkown voice entry type: 51
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Unkown voice entry type: 51
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad programmable Wave pointer "f110f0e"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Unkown voice entry type: 15
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Unkown voice entry type: 27
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Unkown voice entry type: 37
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Unkown voice entry type: 48
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Unkown voice entry type: 51
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Unkown voice entry type: 51
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "1010100"
	voice_square_1 1, 1, 1, 1, 1, 1
	voice_square_1 2, 3, 4, 4, 4, 4
	voice_noise 4, 4, 4, 4, 4
	voice_noise 4, 4, 4, 4, 4
	voice_noise 4, 0, 0, 0, 0
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "1000000"
	voice_square_1 2, 2, 3, 3, 3, 3
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad programmable Wave pointer "3030303"
	voice_noise 5, 5, 5, 5, 5
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Unkown voice entry type: 5
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Unkown voice entry type: 5
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "1010101"
	voice_square_2 2, 2, 2, 2, 2
	voice_square_2 2, 2, 2, 2, 3
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad programmable Wave pointer "4040404"
	voice_noise 4, 4, 4, 4, 4
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_2 2, 2, 2, 2, 2
	voice_square_2 2, 2, 2, 3, 4
	voice_noise 4, 4, 4, 4, 4
	voice_noise 4, 0, 0, 0, 0
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
	voice_square_1 255, 255, 255, 255, 255, 255 		@PLACEHOLDER: Bad sample pointer "0"
