Micolandia_House2_MapScripts::
	.byte 0
	
Micolandia_House2_Girl1_Script::
	msgbox Micolandia_House2_Girl1_Text, MSGBOX_NPC
	release
	end
	
Micolandia_House2_Girl2_Script::
	msgbox Micolandia_House2_Girl2_Text, MSGBOX_NPC
	release
	end
	
Micolandia_House2_Girl1_Text:
	.string "Aún recuerdo la primera vez que\n"
	.string "MICOLO me dijo “Hola reina n.n”.\p"

	.string "¡Eso me encandiló! ¡Oooh!$"
	
Micolandia_House2_Girl2_Text:
	.string "Pero a mi también me dijo lo\n"
	.string "mismo...\p"

	.string "¿MICOLO le dice lo mismo a todas?$"
