#ifndef GUARD_CONSTANTS_BOSS_BATTLES_H
#define GUARD_CONSTANTS_BOSS_BATTLES_H

/*
    Tipos de batalla.
        BATTLE_TYPE_BOSS: combate contra jefe.
        BATTLE_TYPE_TOTEM: combate contra totem.
*/
#define BATTLE_TYPE_NORMAL 0
#define BATTLE_TYPE_BOSS   1
#define BATTLE_TYPE_TOTEM  2

// Boss battles
#define BOSS_BATTLE_TOTEM_SUDOWOODO_DEBUG 1
#define BOSS_BATTLE_CORONA          2
#define BOSS_BATTLE_TOTEM_WINTASS                  3
#define BOSS_BATTLE_TOTEM_TOXTRICITY 4
#define BOSS_BATTLE_TOTEM_COFAGRIGUS 5
#define BOSS_BATTLE_TOTEM_CENTISKORCH 6
#define BOSS_BATTLE_TOTEM_MEGA_GLALIE 7
#define BOSS_BATTLE_TOTEM_TYPHLOSION 8
#define BOSS_BATTLE_TOTEM_MEGA_ABSOL 9
#define BOSS_BATTLE_TOTEM_PROBOPASS 10
#define BOSS_BATTLE_TOTEM_RHYPERIOR 11

// Bosses
#define BOSS_CORONA 1
#define BOSS_YETI   2

// Totems
#define TOTEM_SUDOWOODO_DEBUG 1
#define TOTEM_TOXTRICITY 2
#define TOTEM_COFAGRIGUS 3
#define TOTEM_CENTISKORCH 4
#define TOTEM_WINTASS 5
#define TOTEM_MEGA_GLALIE 6
#define TOTEM_TYPHLOSION 7
#define TOTEM_MEGA_ABSOL 8
#define TOTEM_PROBOPASS 9
#define TOTEM_RHYPERIOR 10

#endif  // GUARD_CONSTANTS_BOSS_BATTLES_H
