GymGooses_MapScripts::
	.byte 0
	
GymGooses_EventScript_GymGuide::
	lock
	faceplayer
	goto_if_set FLAG_DEFEATED_GOOSES_GYM, GymGooses_EventScript_GymGuidePostVictory
	msgbox GymGooses_Text_GymGuideAdvice, MSGBOX_DEFAULT
	release
	end

GymGooses_EventScript_GymGuidePostVictory::
	msgbox GymGooses_Text_GymGuidePostVictory, MSGBOX_DEFAULT
	release
	end

GymGooses_EventScript_LeftGymStatue::
	lockall
	goto_if_set FLAG_DEFEATED_GOOSES_GYM, GymGooses_EventScript_GymStatueCertified
	goto GymGooses_EventScript_GymStatue
	end

GymGooses_EventScript_RightGymStatue::
	lockall
	goto_if_set FLAG_DEFEATED_GOOSES_GYM, GymGooses_EventScript_GymStatueCertified
	goto GymGooses_EventScript_GymStatue
	end

GymGooses_EventScript_GymStatueCertified::
	msgbox GymGooses_Text_GymStatueCertified, MSGBOX_DEFAULT
	releaseall
	end

GymGooses_EventScript_GymStatue::
	msgbox GymGooses_Text_GymStatue, MSGBOX_DEFAULT
	releaseall
	end
	
GymGooses_EventScript_TeleportGirl::
	lock
	faceplayer
	msgbox GymGooses_TeleportGirl_Text, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq GymGooses_EventScript_Entrada
	release
	end
	
GymGooses_EventScript_TeleportBoy::
	lock
	faceplayer
	clearflag FLAG_HIDE_GYMGOOSES_TELEPORTBOY
	msgbox GymGooses_TeleportBoy_Text, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq GymGooses_EventScript_Entrada
	release
	end
	
GymGooses_EventScript_TeleportBoy2::
	lock
	faceplayer
	msgbox GymGooses_TeleportBoy2_Text, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq GymGooses_EventScript_CuartaSala
	release
	end

GymGooses_EventScript_Entrada::
	warp MAP_GYM_GOOSES, 0, 0, 0
	waitstate
	release
	end
	
GymGooses_EventScript_CuartaSala::
	warp MAP_GYM_GOOSES, 2, 0, 0
	waitstate
	release
	end

// Primera, Segunda y Tercera Sala	
GymGooses_CasillaTableroDado::
	msgbox GymGoosesTirarDado_Text, MSGBOX_DEFAULT
	waitmessage
	lock
	faceplayer
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado1_Movement_PlayerDado1
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end

GymGooses_CasillaTableroDado2::
	msgbox GymGoosesTirarDado_Text, MSGBOX_DEFAULT
	waitmessage
	lock
	faceplayer
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado1_Movement_PlayerDado2
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
	
GymGooses_CasillaTableroDado3::
	msgbox GymGoosesTirarDado_Text, MSGBOX_DEFAULT
	waitmessage
	lock
	faceplayer
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado1_Movement_PlayerDado3
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
	
GymGooses_CasillaTableroDado4::
	msgbox GymGoosesTirarDado_Text, MSGBOX_DEFAULT
	waitmessage
	lock
	faceplayer
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado1_Movement_PlayerDado4
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
	
GymGooses_CasillaTableroDado5::
	msgbox GymGoosesTirarDado_Text, MSGBOX_DEFAULT
	waitmessage
	lock
	faceplayer
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado1_Movement_PlayerDado5
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end

GymGooses_CasillaTableroCombate::
	msgbox GymGoosesCombate_Text, MSGBOX_DEFAULT
	lock
	faceplayer
	setflag FLAG_RANDOMBATTLE_GYMGOOSES
	setvar VAR_0x8004, SPECIAL_RANDOM_BATTLE
    setvar VAR_0x8005, 0
    special DoSpecialTrainerBattle
    waitstate
    compare VAR_RESULT, B_OUTCOME_DREW
    call_if_eq CasillaTableroLoss
    compare VAR_RESULT, B_OUTCOME_WON
    call_if_eq CasillaTableroWin
    compare VAR_RESULT, B_OUTCOME_LOST
    call_if_eq CasillaTableroLoss
    compare VAR_RESULT, B_OUTCOME_FORFEITED
    call_if_eq CasillaTableroLoss
CasillaTableroWin::
	clearflag FLAG_RANDOMBATTLE_GYMGOOSES
	msgbox GymGoosesTirarDadoAgain_Text, MSGBOX_DEFAULT
	waitmessage
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado1_Movement_PlayerDadoCombateGanado
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
CasillaTableroLoss::
	special HealPlayerParty
	clearflag FLAG_RANDOMBATTLE_GYMGOOSES
	closemessage
	warp MAP_GYM_GOOSES, 0, 0, 0
	release
	end

GymGooses_CasillaTableroCombate2::
	msgbox GymGoosesCombate_Text, MSGBOX_DEFAULT
	lock
	faceplayer
	setflag FLAG_RANDOMBATTLE_GYMGOOSES
	setvar VAR_0x8004, SPECIAL_RANDOM_BATTLE
    setvar VAR_0x8005, 0
    special DoSpecialTrainerBattle
    waitstate
    compare VAR_RESULT, B_OUTCOME_DREW
    call_if_eq CasillaTableroLoss2
    compare VAR_RESULT, B_OUTCOME_WON
    call_if_eq CasillaTableroWin2
    compare VAR_RESULT, B_OUTCOME_LOST
    call_if_eq CasillaTableroLoss2
    compare VAR_RESULT, B_OUTCOME_FORFEITED
    call_if_eq CasillaTableroLoss2
CasillaTableroWin2::
	clearflag FLAG_RANDOMBATTLE_GYMGOOSES
	msgbox GymGoosesTirarDadoAgain_Text, MSGBOX_DEFAULT
	waitmessage
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado2_Movement_PlayerDadoCombateGanado
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
CasillaTableroLoss2::
	special HealPlayerParty
	clearflag FLAG_RANDOMBATTLE_GYMGOOSES
	closemessage
	warp MAP_GYM_GOOSES, 0, 0, 0
	release
	end
	
GymGooses_CasillaTableroCombate3::
	msgbox GymGoosesCombate_Text, MSGBOX_DEFAULT
	lock
	faceplayer
	setflag FLAG_RANDOMBATTLE_GYMGOOSES
	setvar VAR_0x8004, SPECIAL_RANDOM_BATTLE
    setvar VAR_0x8005, 0
    special DoSpecialTrainerBattle
    waitstate
    compare VAR_RESULT, B_OUTCOME_DREW
    call_if_eq CasillaTableroLoss3
    compare VAR_RESULT, B_OUTCOME_WON
    call_if_eq CasillaTableroWin3
    compare VAR_RESULT, B_OUTCOME_LOST
    call_if_eq CasillaTableroLoss3
    compare VAR_RESULT, B_OUTCOME_FORFEITED
    call_if_eq CasillaTableroLoss3
CasillaTableroWin3::
	clearflag FLAG_RANDOMBATTLE_GYMGOOSES
	msgbox GymGoosesTirarDadoAgain_Text, MSGBOX_DEFAULT
	waitmessage
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado3_Movement_PlayerDadoCombateGanado
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
CasillaTableroLoss3::
	special HealPlayerParty
	clearflag FLAG_RANDOMBATTLE_GYMGOOSES
	closemessage
	warp MAP_GYM_GOOSES, 0, 0, 0
	release
	end
	
GymGooses_CasillaTableroStatus::
	lock
	faceplayer
	msgbox GymGoosesStatus_Text, MSGBOX_DEFAULT
	random 6
	switch VAR_RESULT
	case 0, GymGoosesStatus_Poison_Script
	case 1, GymGoosesStatus_Toxic_Script
	case 2, GymGoosesStatus_Burn_Script
	case 3, GymGoosesStatus_Prz_Script
	case 4, GymGoosesStatus_Slp_Script
	case 5, GymGoosesStatus_Freeze_Script
	end

GymGooses_CasillaTableroPregunta::
	lock
	faceplayer
	setvar VAR_TEMP_1, 0
	msgbox GymGoosesPregunta_Text, MSGBOX_DEFAULT
	random 18
	switch VAR_RESULT
	case 0, Script_Quiz1
	case 1, Script_Quiz2
	case 2, Script_Quiz3
	case 3, Script_Quiz4
	case 4, Script_Quiz5
	case 5, Script_Quiz6
	case 6, Script_Quiz7
	case 7, Script_Quiz8
	case 8, Script_Quiz9
	case 9, Script_Quiz10
	case 10, Script_Quiz11
	case 11, Script_Quiz12
	case 12, Script_Quiz13
	case 13, Script_QuizYESNO1
	case 14, Script_QuizYESNO2
	case 15, Script_QuizYESNO3
	case 16, Script_QuizYESNO4
	case 17, Script_QuizYESNO5
	end
	
GymGooses_CasillaTableroPregunta2::
	lock
	faceplayer
	setvar VAR_TEMP_1, 1
	msgbox GymGoosesPregunta_Text, MSGBOX_DEFAULT
	random 18
	switch VAR_RESULT
	case 0, Script_Quiz1
	case 1, Script_Quiz2
	case 2, Script_Quiz3
	case 3, Script_Quiz4
	case 4, Script_Quiz5
	case 5, Script_Quiz6
	case 6, Script_Quiz7
	case 7, Script_Quiz8
	case 8, Script_Quiz9
	case 9, Script_Quiz10
	case 10, Script_Quiz11
	case 11, Script_Quiz12
	case 12, Script_Quiz13
	case 13, Script_QuizYESNO1
	case 14, Script_QuizYESNO2
	case 15, Script_QuizYESNO3
	case 16, Script_QuizYESNO4
	case 17, Script_QuizYESNO5
	end

GymGooses_CasillaTableroPregunta3::
	lock
	faceplayer
	setvar VAR_TEMP_1, 2
	msgbox GymGoosesPregunta_Text, MSGBOX_DEFAULT
	random 18
	switch VAR_RESULT
	case 0, Script_Quiz1
	case 1, Script_Quiz2
	case 2, Script_Quiz3
	case 3, Script_Quiz4
	case 4, Script_Quiz5
	case 5, Script_Quiz6
	case 6, Script_Quiz7
	case 7, Script_Quiz8
	case 8, Script_Quiz9
	case 9, Script_Quiz10
	case 10, Script_Quiz11
	case 11, Script_Quiz12
	case 12, Script_Quiz13
	case 13, Script_QuizYESNO1
	case 14, Script_QuizYESNO2
	case 15, Script_QuizYESNO3
	case 16, Script_QuizYESNO4
	case 17, Script_QuizYESNO5
	end

GymGooses_CasillaTableroPregunta4::
	lock
	faceplayer
	setvar VAR_TEMP_1, 3
	msgbox GymGoosesPregunta_Text, MSGBOX_DEFAULT
	random 18
	switch VAR_RESULT
	case 0, Script_Quiz1
	case 1, Script_Quiz2
	case 2, Script_Quiz3
	case 3, Script_Quiz4
	case 4, Script_Quiz5
	case 5, Script_Quiz6
	case 6, Script_Quiz7
	case 7, Script_Quiz8
	case 8, Script_Quiz9
	case 9, Script_Quiz10
	case 10, Script_Quiz11
	case 11, Script_Quiz12
	case 12, Script_Quiz13
	case 13, Script_QuizYESNO1
	case 14, Script_QuizYESNO2
	case 15, Script_QuizYESNO3
	case 16, Script_QuizYESNO4
	case 17, Script_QuizYESNO5
	end

GymGooses_CasillaTableroPregunta5::
	lock
	faceplayer
	setvar VAR_TEMP_1, 4
	msgbox GymGoosesPregunta_Text, MSGBOX_DEFAULT
	random 18
	switch VAR_RESULT
	case 0, Script_Quiz1
	case 1, Script_Quiz2
	case 2, Script_Quiz3
	case 3, Script_Quiz4
	case 4, Script_Quiz5
	case 5, Script_Quiz6
	case 6, Script_Quiz7
	case 7, Script_Quiz8
	case 8, Script_Quiz9
	case 9, Script_Quiz10
	case 10, Script_Quiz11
	case 11, Script_Quiz12
	case 12, Script_Quiz13
	case 13, Script_QuizYESNO1
	case 14, Script_QuizYESNO2
	case 15, Script_QuizYESNO3
	case 16, Script_QuizYESNO4
	case 17, Script_QuizYESNO5
	end			
	
Script_Quiz1::	
	msgbox Quiz1_Text, MSGBOX_DEFAULT
	multichoice 12, 0, MULTI_QUIZ1_GYM, 1
	switch VAR_RESULT
	case 0, GymGooses_EventScript_Incorrecta
	case 1, GymGooses_EventScript_Correcta
	case 2, GymGooses_EventScript_Incorrecta
	case MULTI_B_PRESSED, NoSabeNoContesta
	end
	
Script_Quiz2::	
	msgbox Quiz2_Text, MSGBOX_DEFAULT
	multichoice 12, 0, MULTI_QUIZ2_GYM, 1
	switch VAR_RESULT
	case 0, GymGooses_EventScript_Correcta
	case 1, GymGooses_EventScript_Incorrecta
	case 2, GymGooses_EventScript_Incorrecta
	case MULTI_B_PRESSED, NoSabeNoContesta
	end
	
Script_Quiz3::	
	msgbox Quiz3_Text, MSGBOX_DEFAULT
	multichoice 12, 0, MULTI_QUIZ3_GYM, 1
	switch VAR_RESULT
	case 0, GymGooses_EventScript_Correcta
	case 1, GymGooses_EventScript_Incorrecta
	case 2, GymGooses_EventScript_Incorrecta
	case MULTI_B_PRESSED, NoSabeNoContesta
	end
	
Script_Quiz4::	
	msgbox Quiz4_Text, MSGBOX_DEFAULT
	multichoice 12, 0, MULTI_QUIZ4_GYM, 1
	switch VAR_RESULT
	case 0, GymGooses_EventScript_Incorrecta
	case 1, GymGooses_EventScript_Correcta
	case 2, GymGooses_EventScript_Incorrecta
	case MULTI_B_PRESSED, NoSabeNoContesta
	end
	
Script_Quiz5::	
	msgbox Quiz5_Text, MSGBOX_DEFAULT
	multichoice 12, 0, MULTI_QUIZ5_GYM, 1
	switch VAR_RESULT
	case 0, GymGooses_EventScript_Correcta
	case 1, GymGooses_EventScript_Incorrecta
	case 2, GymGooses_EventScript_Incorrecta
	case MULTI_B_PRESSED, NoSabeNoContesta
	end
	
Script_Quiz6::	
	msgbox Quiz6_Text, MSGBOX_DEFAULT
	multichoice 12, 0, MULTI_QUIZ6_GYM, 1
	switch VAR_RESULT
	case 0, GymGooses_EventScript_Incorrecta
	case 1, GymGooses_EventScript_Correcta
	case 2, GymGooses_EventScript_Incorrecta
	case MULTI_B_PRESSED, NoSabeNoContesta
	end
	
Script_Quiz7::	
	msgbox Quiz7_Text, MSGBOX_DEFAULT
	multichoice 12, 0, MULTI_QUIZ7_GYM, 1
	switch VAR_RESULT
	case 0, GymGooses_EventScript_Correcta
	case 1, GymGooses_EventScript_Correcta
	case 2, GymGooses_EventScript_Correcta
	case MULTI_B_PRESSED, NoSabeNoContesta
	end
	
Script_Quiz8::	
	msgbox Quiz8_Text, MSGBOX_DEFAULT
	multichoice 12, 0, MULTI_QUIZ8_GYM, 1
	switch VAR_RESULT
	case 0, GymGooses_EventScript_Correcta
	case 1, GymGooses_EventScript_Incorrecta
	case 2, GymGooses_EventScript_Incorrecta
	case MULTI_B_PRESSED, NoSabeNoContesta
	end
	
Script_Quiz9::	
	msgbox Quiz9_Text, MSGBOX_DEFAULT
	multichoice 12, 0, MULTI_QUIZ9_GYM, 1
	switch VAR_RESULT
	case 0, GymGooses_EventScript_Incorrecta
	case 1, GymGooses_EventScript_Correcta
	case 2, GymGooses_EventScript_Incorrecta
	case MULTI_B_PRESSED, NoSabeNoContesta
	end
	
Script_Quiz10::	
	msgbox Quiz10_Text, MSGBOX_DEFAULT
	multichoice 12, 0, MULTI_QUIZ10_GYM, 1
	switch VAR_RESULT
	case 0, GymGooses_EventScript_Incorrecta
	case 1, GymGooses_EventScript_Incorrecta
	case 2, GymGooses_EventScript_Correcta
	case MULTI_B_PRESSED, NoSabeNoContesta
	end
	
Script_Quiz11::	
	msgbox Quiz11_Text, MSGBOX_DEFAULT
	multichoice 12, 0, MULTI_QUIZ11_GYM, 1
	switch VAR_RESULT
	case 0, GymGooses_EventScript_Incorrecta
	case 1, GymGooses_EventScript_Incorrecta
	case 2, GymGooses_EventScript_Correcta
	case MULTI_B_PRESSED, NoSabeNoContesta
	end
	
Script_Quiz12::	
	msgbox Quiz12_Text, MSGBOX_DEFAULT
	multichoice 12, 0, MULTI_QUIZ12_GYM, 1
	switch VAR_RESULT
	case 0, GymGooses_EventScript_Incorrecta
	case 1, GymGooses_EventScript_Incorrecta
	case 2, GymGooses_EventScript_Correcta
	case MULTI_B_PRESSED, NoSabeNoContesta
	end
	
Script_Quiz13::	
	msgbox Quiz13_Text, MSGBOX_DEFAULT
	multichoice 12, 0, MULTI_QUIZ13_GYM, 1
	switch VAR_RESULT
	case 0, GymGooses_EventScript_Incorrecta
	case 1, GymGooses_EventScript_Correcta
	case 2, GymGooses_EventScript_Incorrecta
	case MULTI_B_PRESSED, NoSabeNoContesta
	end
	
Script_QuizYESNO1::	
	msgbox Quiz14_Text, MSGBOX_YESNO
	switch VAR_RESULT
	case NO, GymGooses_EventScript_Correcta
	goto GymGooses_EventScript_Incorrecta
	end
	
Script_QuizYESNO2::	
	msgbox Quiz15_Text, MSGBOX_YESNO
	switch VAR_RESULT
	case NO, GymGooses_EventScript_Correcta
	goto GymGooses_EventScript_Incorrecta
	end
	
Script_QuizYESNO3::	
	msgbox Quiz16_Text, MSGBOX_YESNO
	switch VAR_RESULT
	case NO, GymGooses_EventScript_Correcta
	msgbox Quiz16_Text_Correcta, MSGBOX_DEFAULT
	goto GymGooses_EventScript_Incorrecta
	end
	
Script_QuizYESNO4::	
	msgbox Quiz17_Text, MSGBOX_YESNO
	switch VAR_RESULT
	case YES, GymGooses_EventScript_Correcta
	goto GymGooses_EventScript_Incorrecta
	end
	
Script_QuizYESNO5::	
	msgbox Quiz18_Text, MSGBOX_YESNO
	switch VAR_RESULT
	case YES, GymGooses_EventScript_Correcta
	goto GymGooses_EventScript_Incorrecta
	end

GymGooses_EventScript_Incorrecta::
	msgbox Respuesta_Incorrecta_Text
	goto CasillaTableroIncorrecta_EventScript

GymGooses_EventScript_Correcta::
	msgbox Respuesta_Correcta_Text	
	goto CasillaTableroCorrecta_EventScript
	
NoSabeNoContesta::
	msgbox Respuesta_NSNC_Text
	goto NoSabeNoContesta_2

CasillaTableroCorrecta_EventScript::
	switch VAR_TEMP_1
	case 0, CasillaTableroCorrectaCasilla1_EventScript
	case 1, CasillaTableroCorrectaCasilla2_EventScript
	case 2, CasillaTableroCorrectaCasilla3_EventScript
	case 3, CasillaTableroCorrectaCasilla4_EventScript
	case 4, CasillaTableroCorrectaCasilla5_EventScript
	end
	
CasillaTableroCorrectaCasilla1_EventScript::
	msgbox GymGoosesTirarDadoAgain_Text, MSGBOX_DEFAULT
	waitmessage
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado1_Movement_PlayerDadoPreguntaCorrecta
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
	
CasillaTableroCorrectaCasilla2_EventScript::
	msgbox GymGoosesTirarDadoAgain_Text, MSGBOX_DEFAULT
	waitmessage
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado2_Movement_PlayerDadoPreguntaCorrecta
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
	
CasillaTableroCorrectaCasilla3_EventScript::
	msgbox GymGoosesTirarDadoAgain_Text, MSGBOX_DEFAULT
	waitmessage
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado3_Movement_PlayerDadoPreguntaCorrecta
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
	
CasillaTableroCorrectaCasilla4_EventScript::
	msgbox GymGoosesTirarDadoAgain_Text, MSGBOX_DEFAULT
	waitmessage
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado4_Movement_PlayerDadoPreguntaCorrecta
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
	
CasillaTableroCorrectaCasilla5_EventScript::
	msgbox GymGoosesTirarDadoAgain_Text, MSGBOX_DEFAULT
	waitmessage
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado5_Movement_PlayerDadoPreguntaCorrecta
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
	
CasillaTableroIncorrecta_EventScript::
	closemessage
	warp MAP_GYM_GOOSES, 0, 0, 0
	release
	end
	
NoSabeNoContesta_2::
	closemessage
	warp MAP_GYM_GOOSES, 0, 0, 0
	release
	end

//Dado primera casilla
GymGoosesDado1_Movement_PlayerDado1:
	walk_left
	walk_left
	walk_left
	walk_up
	walk_up
	walk_up
	step_end

//Dado segunda casilla
GymGoosesDado1_Movement_PlayerDado2:
	walk_up
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	step_end
	
//Dado tercera casilla
GymGoosesDado1_Movement_PlayerDado3:
	walk_right
	walk_right
	walk_right
	walk_right
	walk_down
	walk_down
	step_end
	
//Dado cuarta casilla
GymGoosesDado1_Movement_PlayerDado4:
	walk_right
	walk_down
	walk_down
	walk_right
	walk_right
	walk_right
	step_end

//Dado quinta casilla	
GymGoosesDado1_Movement_PlayerDado5:
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	step_end
	
//Dado primera casilla combate ganado
GymGoosesDado1_Movement_PlayerDadoCombateGanado:
	walk_left
	walk_up
	walk_up
	walk_up
	walk_right
	walk_right
	step_end

//Dado segunda casilla combate ganado
GymGoosesDado2_Movement_PlayerDadoCombateGanado:
	walk_right
	walk_right
	walk_down
	walk_down
	walk_right
	walk_right
	step_end

//Dado tercera casilla combate ganado
GymGoosesDado3_Movement_PlayerDadoCombateGanado:
	walk_down
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	step_end

//Dado primera casilla respuesta correcta
GymGoosesDado1_Movement_PlayerDadoPreguntaCorrecta:
	walk_left
	walk_left
	walk_up
	walk_up
	walk_up
	walk_right
	step_end

//Dado segunda casilla respuesta correcta
GymGoosesDado2_Movement_PlayerDadoPreguntaCorrecta:
	walk_up
	walk_up
	walk_right
	walk_right
	walk_right
	walk_right
	step_end

//Dado tercera casilla respuesta correcta
GymGoosesDado3_Movement_PlayerDadoPreguntaCorrecta:
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	walk_down
	step_end
	
//Dado cuarta casilla respuesta correcta
GymGoosesDado4_Movement_PlayerDadoPreguntaCorrecta:
	walk_right
	walk_right
	walk_right
	walk_down
	walk_down
	walk_right
	step_end
	
//Dado quinta casilla respuesta correcta
GymGoosesDado5_Movement_PlayerDadoPreguntaCorrecta:
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	step_end
	
//Dado casillas Status
GymGoosesDado1_Movement_PlayerDadoStatus:
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	step_end

GymGoosesStatus_Poison_Script::
	special PoisonMons
	msgbox GymGoosesStatus_Poison
	waitse
	msgbox GymGoosesTirarDadoStatus_Text, MSGBOX_DEFAULT
	closemessage
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado1_Movement_PlayerDadoStatus
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
	
GymGoosesStatus_Toxic_Script::
	special ToxicMons
	msgbox GymGoosesStatus_Toxic
	waitse
	msgbox GymGoosesTirarDadoStatus_Text, MSGBOX_DEFAULT
	closemessage
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado1_Movement_PlayerDadoStatus
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
	
GymGoosesStatus_Slp_Script::
	special SleepMons
	msgbox GymGoosesStatus_Slp
	waitse
	msgbox GymGoosesTirarDadoStatus_Text, MSGBOX_DEFAULT
	closemessage
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado1_Movement_PlayerDadoStatus
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
	
GymGoosesStatus_Prz_Script::
	special ParalisisMons
	msgbox GymGoosesStatus_Prz
	waitse
	msgbox GymGoosesTirarDadoStatus_Text, MSGBOX_DEFAULT
	closemessage
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado1_Movement_PlayerDadoStatus
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
	
GymGoosesStatus_Burn_Script::
	special BurnMons
	msgbox GymGoosesStatus_Burn
	waitse
	msgbox GymGoosesTirarDadoStatus_Text, MSGBOX_DEFAULT
	closemessage
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado1_Movement_PlayerDadoStatus
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end
	
GymGoosesStatus_Freeze_Script::
	special FreezeMons
	msgbox GymGoosesStatus_Freeze
	waitse
	msgbox GymGoosesTirarDadoStatus_Text, MSGBOX_DEFAULT
	closemessage
	random 6
	addvar VAR_RESULT, 1
	copyvar VAR_0x8004, VAR_RESULT
	special Buffer0x8004VarToStringVar1
	msgbox gText_DiceResult, MSGBOX_DEFAULT
	waitmessage
	applyrangemovement EVENT_OBJ_ID_PLAYER, GymGoosesDado1_Movement_PlayerDadoStatus
	waitmovement 0
	special DoApplyrangemovementLastStep
	release
	end

// Cuarta Sala
    @ Combate contra totem.
GymGooses_EventScript_Totem:: @ 8237725
	lockall
	clearflag FLAG_HIDE_GYMGOOSES_TELEPORTBOY
	playmoncry SPECIES_MEGA_GLALIE, 2
	delay 40
	waitmoncry
	msgbox GymGooses_Text_Totemaparece, MSGBOX_DEFAULT
    setvar VAR_0x8004, BOSS_BATTLE_TOTEM_MEGA_GLALIE
    special CreateBossBattleMon
    special BattleSetup_StartBossBattle
    waitstate
    setvar VAR_LAST_TALKED, 1
    specialvar VAR_RESULT, GetBattleOutcome
	removeobject 2
	removeobject 3
	setflag FLAG_TOTEM_GYMGOOSES
    msgbox GymGooses_Text_Totemderrotado
	releaseall
	end
    @ Combate contra totem.	
	
// Quinta Sala
GymGooses_EventScript_Gooses::
	trainerbattle_single TRAINER_GOOSES, GymGooses_Text_GoosesIntro, GymGooses_Text_GoosesDefeat, GymGooses_EventScript_GoosesDefeated, NO_MUSIC
	release
	end
	
GymGooses_EventScript_GoosesDefeated::
	message GymGooses_Text_ReceivedBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	msgbox GymGooses_Text_ExplainBadgeTakeThis, MSGBOX_DEFAULT
	setflag FLAG_DEFEATED_GOOSES_GYM
	delay 30
	release
	end
	
GymGooses_EventScript_Primera_Casilla_Prueba::
	lockall
	goto_if_set FLAG_DEFEATED_GOOSES_GYM, GymGooses_EventScript_GymComplete
	msgbox GymGooses_Text_Comienza, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq GymGooses_EventScript_Comienza2
	applymovement EVENT_OBJ_ID_PLAYER, GymGoosesNOComienzPrueba
	waitmovement 0
	releaseall
	end
GymGooses_EventScript_Comienza2::
	msgbox GymGooses_Text_Curacion, MSGBOX_DEFAULT
	special HealPlayerParty
	applymovement EVENT_OBJ_ID_PLAYER, GymGoosesComienzPrueba
	waitmovement 0
	releaseall
	end
	
GymGooses_EventScript_GymComplete::
	msgbox GymGooses_Text_Jugardenuevo, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq GymGooses_EventScript_Comienza2
	applymovement EVENT_OBJ_ID_PLAYER, GymGoosesNOComienzPrueba
	waitmovement 0
	releaseall
	end
	
GymGoosesComienzPrueba:
	walk_up
	step_end
	
GymGoosesNOComienzPrueba:
	walk_down
	step_end

GymGoosesTirarDado_Text:
	.string "Casilla Dado: ¡Tira el dado!$"
	
GymGoosesTirarDadoAgain_Text:
	.string "Has superado la prueba:\n"
	.string "¡Tira el dado otra vez!$"
	
GymGoosesTirarDadoStatus_Text:
	.string "¡Tira el dado otra vez!$"
	
GymGoosesCombate_Text:
	.string "Casilla Pokeball:\n"
	.string "¡Deberás vencer a un entrenador\l"
	.string "que usará un equipo creado\l"
	.string "de forma aleatoria!$"
	
GymGoosesStatus_Text:
	.string "Casilla Status:\n"
	.string "¡Probablemente tus POKÉMON sufrirán\l"
	.string "un estado pernicioso!$"
	
GymGoosesStatus_Poison:
	.string "¡ENVENENATE!$"
	
GymGoosesStatus_Toxic:
	.string "¡INTOXICATE!$"
	
GymGoosesStatus_Slp:
	.string "¡DUERMETE!$"
	
GymGoosesStatus_Prz:
	.string "¡PARALIZATE!$"
	
GymGoosesStatus_Burn:
	.string "¡QUEMATE!$"
	
GymGoosesStatus_Freeze:
	.string "¡CONGÉLATE!$"
	
GymGoosesPregunta_Text:
	.string "Casilla Pregunta:\n"
	.string "¡Debes responder de forma correcta\l" 
	.string "a la siguiente pregunta!$"
	
Quiz1_Text:
	.string "¿Quién no pudo abrir un .ZIP?$"

Quiz2_Text:	
	.string "¿Quien lideró la Bronyficación por\n" 
	.string "medio de un Golpe de Estado en PxP?$"
	
Quiz3_Text:
	.string "¿Quién se equivocó de SET de\n"
	.string "GYARADOS en un torneo?$"
	
Quiz4_Text:
	.string "¿Quién dió una PATADA SALTO a\n" 
	.string "una pobre papelera?$"
	
Quiz5_Text:
	.string "¿Quién dijo la frase:\n"
	.string "Arena, eres un mierdas?$"

Quiz6_Text:
	.string "¿Quién se considera el mayor\n" 
	.string "fan de PROBOPASS?$"
	
Quiz7_Text:
	.string "¿Qué esperamos ver todos en\n" 
	.string "un NUZLOCKE de EEVEETO?$"
	
Quiz8_Text:
	.string "Según un usuario de PxP,\n" 
	.string "¿de qué tipo es ENTEI?$"
	
Quiz9_Text:
	.string "¿Por qué MONOCICLO?$"
	
Quiz10_Text:
	.string "¿Quién creó la prestigiosa\n"
	.string "GUARDERIA MIDELE?$"

Quiz11_Text:
	.string "¿Quién fué baneado recibiendo\n"
	.string "Una cantidad de -100 Karma?$"

Quiz12_Text:
	.string "¿Qué significa el título\n"
	.string "No Person?$"
	
Quiz13_Text:
	.string "¿Cuál es el POKÉMON capaz de\n" 
	.string "usar el Trueno de la Oscuridad\l" 
	.string "(DARK THUNDER)?$"

Quiz14_Text:
	.string "¿PHENT es una multicuenta\n" 
	.string "de KADERETE?$"
	
Quiz15_Text:
	.string "Según GHADDAR, ¿los juegos\n"
	.string "de la saga principal de\l"
	.string "Final Fantasy son RPGs?$"
	
Quiz16_Text:
	.string "¿Fué MELKOR el genuino creador\n"
	.string "del Off Off Topic (OOT) de PxP?$"
	
Quiz16_Text_Correcta:
	.string "¡El genuino creador del OOT\n"
	.string "fué MICHOH!$"
	
Quiz17_Text:
	.string "¿felipex88 se cortó la lengua?\n"
	.string "por gusto? O eso dijo.$"
	
Quiz18_Text:
	.string "¿El último OOT fue el MCCLVIII?$"
	
Respuesta_Incorrecta_Text:
	.string "¡RESPUESTA INCORRECTA!$"
	
Respuesta_Correcta_Text:
	.string "¡CORRECTO!$"
	
Respuesta_NSNC_Text:
	.string "¡Has evitado responder!$"
	
GymGooses_Text_GymGuideAdvice:
	.string "¡Ya veo que has llegado lejos!\p"
	
	.string "Bienvenido al último GYM de MICOLANDIA.\p"

	.string "La pruebas de este GYM son:\n"
	.string "Completar los 3 TABLEROS de DADOS\l"
	.string "Derrotar al POKÉMON TOTEM\l"
	.string "Derrotar al LIDER de GYM\p"
	
	.string "Si consigues superar las pruebas,\n"
	.string "se te recompensará con la no-oficial\l"
	.string "MEDALLA FRÍO INVERNAL.\p"

	.string "Bien, te voy a explicar en que consiste\n"
	.string "la prueba principal: TABLERO de DADOS.\p"
	
	.string "El tablero de dados consiste en avanzar\n"
	.string "casillas usando dados aleatorios del\l"
	.string "1 al 6.\p"
	
	.string "Avanzarás casillas según el número que\n"
	.string "aparezca, pero tendrás que afrontar\l"
	.string "desafios según la casilla en la que\l"
	.string "caigas.\p"
	
	.string "Te explicaré la función de cada casilla:\p"

	.string "Casilla Naranja: Te permite tirar un dado\n"
	.string "del 1 al 6.\p"
	
	.string "Casilla Direccional: Te permite avanzar\n"
	.string "una casilla.\p"

	.string "Casilla Salto: Nada útil, solo haces que\n"
	.string "des un salto en el sitio.\p"

	.string "Casilla Pokéball: Combatirás contra\n"
	.string "un entrenador generado con un equipo\l"
	.string "generado de forma aleatoria.\p"

	.string "Casilla Morada: Tendrás que responder de\n"
	.string "forma correcta a una pregunta.\p"

	.string "Casilla Musical: Tus pokémon pueden\n"
	.string "caer en un estado alterado aleatorio.\p"	

	.string "En cuanto al LIDER GOOSES, solo te puedo\n"
	.string "decir... ¡Que tengas mucho cuidado\l" 
	.string "con las congelaciones!\p"

	.string "¡Buen hax!$"

GymGooses_Text_GymGuidePostVictory:
	.string "¡Enhorabuena! ¡Has vencido a\n"
	.string "todos los lideres de GYM!\p"

	.string "¡Ya puedes participar\n"
	.string "en la MICOLIGA!\p"
	
	.string "¡Buen hax!$"	
	
GymGooses_Text_GymStatue:
	.string "POKEMON GYM Nº3\n"
	.string "LEADER: GOOSES\l"
	.string "“TEMÁTICA: FRÍO INVERNAL”$"

GymGooses_Text_GymStatueCertified:
	.string "POKEMON GYM Nº3\n"
	.string "LEADER: GOOSES\l"
	.string "“TEMÁTICA: FRÍO INVERNAL”\p"

	.string "GOOSES'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"
	
GymGooses_TeleportGirl_Text:
	.string "Si quieres salir del GYM, te puedo\n"
	.string "regresar a la entrada, pero ten en\l"
	.string "cuenta que tendrás que empezar el\l"
	.string "tablero desde el principio.\p"

	.string "¿Quieres que te lleve a la entrada\n"
	.string "del GYM?$"
	
GymGooses_TeleportBoy_Text:
	.string "¡Vaya! ¡Así que has superado\n"
	.string "los 3 tableros de dados logrando\l"
	.string "llegar hasta la Cuarta Sala!\p"
	
	.string "¡Mis más sinceras felicitaciones!\p"

	.string "Por cierto, si quieres salir\n"
	.string "del GYM, te puedo regresar a la\l"
	.string "entrada. Eso si, ahora podrás\l" 
	.string "volver a esta misma sala con la\l"
	.string "ayuda de mi otro compañero.\p"

	.string "¿Quieres que te lleve a la entrada\n"
	.string "del GYM?$"
	
GymGooses_TeleportBoy2_Text:
	.string "Debido a que has superado los\n"
	.string "3 tableros de dados, ahora puedes\l"
	.string "elegir entre superar de nuevo los\l"
	.string "tableros o hacer que te lleve de\l"
	.string "nuevo a la Cuarta Sala.\p"

	.string "¿Quieres que te lleve a la Cuarta\n"
	.string "Sala del GYM?$"
	
GymGooses_Text_GoosesIntro:
	.string "FRASES$"
	
GymGooses_Text_GoosesDefeat:
	.string "FRASES$"
	
GymGooses_Text_GoosesPostBattle:
	.string "FRASES$"
	
GymGooses_Text_ReceivedBadge:
	.string "{PLAYER} recibió la MEDALLA FRÍO\n"
	.string "INVERNAL de GOOSES.$"

GymGooses_Text_ExplainBadgeTakeThis:
	.string "Con esta MEDALLA en tu poder, estás\n"
	.string "capacitado para afrontar el reto de\l" 
	.string "DARKIZARD, en el último GYM.\p"
	
	.string "El HATE sobre DPP que él desborda\n"
	.string "lo ha transformado en GYMNASIO\p"
	
	.string "Mucha suerte, ¡La necesitarás!$"
	
GymGooses_Text_Totemaparece:
	.string "M-GLALIE, the Totem Pokémon\n"
	.string "has appeared!$"
	
GymGooses_Text_Totemderrotado:
	.string "M-GLALIE disappeared...$"
	
GymGooses_Text_Comienza:
	.string "¿Estás preparado para comenzar\n"
	.string "la prueba del GYM?$"
	
GymGooses_Text_Jugardenuevo:
	.string "Debido a que has completado el GYM,\n" 
	.string "ahora podrás jugar la prueba del\l"
	.string "tablero todas las veces que quieras,\l"
	.string "pero sin ningún premio a conseguir.\p"
	
	.string "¿Estás preparado para comenzar\n"
	.string "la prueba?$"
	
GymGooses_Text_Curacion:
	.string "Antes de comenzar la prueba,\n"
	.string "tu equipo será curado.\p"
	
	.string "¡ADELANTE!$"
