IzabeIsland_House3_MapScripts::
	.byte 0


IzabeIsland_House3_EventScript_Scientist::
	msgbox IzabeIsland_House3_Text_Scientist, MSGBOX_NPC
	end

IzabeIsland_House3_EventScript_Kanto1::
	msgbox IzabeIsland_House3_Text_Kanto1, MSGBOX_SIGN
	end

IzabeIsland_House3_EventScript_Johto1::
	msgbox IzabeIsland_House3_Text_Johto1, MSGBOX_SIGN
	end

IzabeIsland_House3_EventScript_StackOfBooks::
	msgbox IzabeIsland_House3_Text_StackOfBooks, MSGBOX_SIGN
	end

IzabeIsland_House3_EventScript_Bookshelf::
	msgbox IzabeIsland_House3_Text_Bookshelf, MSGBOX_SIGN
	end

IzabeIsland_House3_EventScript_Izabe1::
	msgbox IzabeIsland_House3_Text_Izabe1, MSGBOX_SIGN
	end

IzabeIsland_House3_EventScript_Izabe2::
	msgbox IzabeIsland_House3_Text_Izabe2, MSGBOX_SIGN
	end

IzabeIsland_House3_Text_Scientist::
	.string "Mmm...\n"
	.string "¿Sabes donde nos encontramos?\l"
	.string "Esto es el LABORATORIO de MICOLO.\p"
	.string "Hace tiempo, MICOLO, el científico más\n"
	.string "destacado de la ISLA vivía aquí.\l"
	.string "Sin embargo, un día ocurrió un incidente\l"
	.string "y no se volvió a ver a MICOLO...\p"
	.string "Si quieres saber más, puedes investigar\n"
	.string "el laboratorio. Tal vez encuentres algún\l"
	.string "documento interesante...$"

IzabeIsland_House3_Text_Kanto1::
	.string "Hay un documento abierto en el PC.\n"
	.string "“Diario de MICOLO: KANTO”\p"
	.string "“Junto a la ayuda de la MAFIA, fui capaz\n"
	.string "de controlar KANTO y establecer mi\l"
	.string "GUARIDA en las profundidades de CUEVA\l"
	.string "CELESTE. n.n”\p"
	.string "“Sin embargo, la POLICÍA de KANTO cercó\n"
	.string "a la MAFIA y cierta persona entrometida\l"
	.string "logró derrotarme.”\p"
	.string "“Pero no pasa nada, iré a JOHTO y crearé\n"
	.string "mi GUARDERÍA MIDELE n.n”\p"
	.string "“PD: Tonto el que lo lea xDDDDDDDDDDDDD”$"

IzabeIsland_House3_Text_Johto1::
	.string "Hay un documento abierto en el PC.\n"
	.string "“Diario de MICOLO: JOHTO”\p"
	.string "“He establecido la GUARIDA MIDELE\n"
	.string "exitosamente en JOHTO. n.n”\l"
	.string "“Sin embargo, alguien ha logrado entrar\l"
	.string "y derrotarme otra vez. LOOOOOOL.”\p"
	.string "“La ayuda de FURRY ha sido inútil.”\n"
	.string "“Tras mi segunda derrota, no me queda\l"
	.string "más remedio que volver a IZABE. n.n”\p"
	.string "“PD: Tonto el que lo lea xDDDDDDDDDDDDD”$"

IzabeIsland_House3_Text_StackOfBooks::
	.string "Hay una pila de libros en el suelo.\n"
	.string "Entre ellos hay una copia del libro\l"
	.string "maldito, el MICONOMICÓN.$"

IzabeIsland_House3_Text_Bookshelf::
	.string "Hay un montón de libros. Entre ellos\n"
	.string "lees títulos como “Hola reina: n.n” y\l"
	.string "“PKHex: guía para novatos”.$"

IzabeIsland_House3_Text_Izabe1::
	.string "Hay un documento abierto en el PC.\n"
	.string "“INVESTIGACIÓN 1: IZABE”\p"
	.string "“Necesitaré diversas máquinas para el\n"
	.string "comienzo de investigación. n.n”\l"
	.string "“He decidido almacenarlas en una casa\l"
	.string "abandonada de la isla. n.n”\l"
	.string "“Solo se puede acceder por la parte de\l"
	.string "atrás, así que no creo que nadie las\l"
	.string "encuentre. n.n”\p"
	.string "“PD: Tonto el que lo lea xDDDDDDDDDDDDD”$"

IzabeIsland_House3_Text_Izabe2::
	.string "Hay un documento abierto en el PC.\n"
	.string "“INVESTIGACIÓN 2: IZABE”\p"
	.string "“Necesitaré una gran fuente de energía\n"
	.string "para realizar los experimentos. n.n”\l"
	.string "“He decidido utilizar el viejo generador\l"
	.string "abandonada de la isla. n.n”\l"
	.string "“Solo se puede acceder por el lago de la\l"
	.string "isla, así que no creo que nadie sea\l"
	.string "capaz de bucear hasta allí. n.n”\p"
	.string "“PD: Tonto el que lo lea xDDDDDDDDDDDDD”$"
