IzabeIsland_Exterior_MapScripts::
	.byte 0

IzabeIslandExterior_EventScript_Guard::
	msgbox IzabeIslandExterior_Text_Guard, MSGBOX_NPC
	end
	
IzabeIslandExterior_Text_Guard::
	.string "Estás en ISLA IZABLE.\n"
	.string "Desde tiempos inmemoriales, esta isla\p"
	.string "ha estado azotada por nevadas y\n"
	.string "ventiscas. Si has llegado hasta aquí,\p"
	.string "es que eres fuerte.\n"
	.string "De todas formas, ten cuidado.$"
