IzabeIsland_Exterior_MapScripts::
	.byte 0

IzabeIslandExterior_EventScript_Guard::
	msgbox IzabeIslandExterior_Text_Guard, MSGBOX_NPC
	end
	
IzabeIslandExterior_Text_Guard::
	.string "Estás en IZABE ISLAND.\n"
	.string "Desde tiempos inmemoriales, esta isla\l"
	.string "ha estado azotada por nevadas y\p"
	.string "ventiscas. Si has llegado hasta aquí,\n"
	.string "es que eres fuerte.\p"
	.string "De todas formas, ten cuidado.$"
